# Generated by Django 5.1 on 2026-04-24 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='official_receipt_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
