# Generated by Django 5.1 on 2026-04-29 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_receipt_official_receipt_no_receipt_receipt_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='atp_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='receipt',
            name='officer_receiving',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='receipt',
            name='payment_stamp',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='receipt',
            name='practitioner_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='receipt',
            name='provincial_treasury_office',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to=settings.AUTH_USER_MODEL),
        ),
    ]
