# Generated by Django 5.1 on 2026-04-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_receipt_atp_number_receipt_officer_receiving_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationGuideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('audience', models.CharField(choices=[('general', 'General'), ('graduand', 'Graduand'), ('nurse', 'Nurse'), ('doctor', 'Doctor'), ('chw', 'Community Health Worker'), ('nurse_aide', 'Nurse Aide')], default='general', max_length=30)),
                ('summary', models.TextField(blank=True)),
                ('required_fields', models.JSONField(blank=True, default=list)),
                ('action_url_name', models.CharField(blank=True, max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['audience', 'display_order', 'code'],
                'unique_together': {('code', 'audience')},
            },
        ),
    ]
