# Generated by Django 5.1 on 2026-05-21 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_registrationguideline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportFreshnessState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_key', models.CharField(choices=[('monthly_analytics', 'Monthly Analytics'), ('yearly_analytics', 'Yearly Analytics'), ('financial_forecast', 'Financial Forecast'), ('registered_nurses', 'Registered Nurses'), ('minister_brief', 'Minister Brief'), ('registrar_secretary_brief', 'Registrar / Secretary Brief'), ('production_readiness', 'Production Readiness')], max_length=80)),
                ('scope', models.CharField(choices=[('all', 'All Regulatory Offices'), ('nursing', 'Nursing Council'), ('medical', 'Medical Board')], default='all', max_length=20)),
                ('data_version', models.PositiveIntegerField(default=0)),
                ('last_data_changed_at', models.DateTimeField(blank=True, null=True)),
                ('last_data_change_reason', models.CharField(blank=True, max_length=255)),
                ('last_data_change_source', models.CharField(blank=True, max_length=255)),
                ('last_generated_at', models.DateTimeField(blank=True, null=True)),
                ('last_generated_output', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['report_key', 'scope'],
                'unique_together': {('report_key', 'scope')},
            },
        ),
    ]
