import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_reportfreshnessstate'),
        ('workforce', '0028_alter_practicinglicenserecord_record_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NursingAnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source_file_name', models.CharField(max_length=255)),
                ('source_file_path', models.TextField(blank=True)),
                ('source_file_hash', models.CharField(db_index=True, max_length=64)),
                ('workbook_generated_on', models.DateField(blank=True, null=True)),
                ('workbook_title', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('total_sheets', models.PositiveIntegerField(default=0)),
                ('processed_sheets', models.PositiveIntegerField(default=0)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('imported_rows', models.PositiveIntegerField(default=0)),
                ('sheet_row_counts', models.JSONField(blank=True, default=dict)),
                ('kpi_summary', models.JSONField(blank=True, default=dict)),
                ('filter_options', models.JSONField(blank=True, default=dict)),
                ('import_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('source_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nursing_analytics_snapshots', to='workforce.dataimportbatch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NursingLifecycleFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=80)),
                ('lifecycle_stage', models.CharField(db_index=True, max_length=80)),
                ('licence_status', models.CharField(blank=True, max_length=100)),
                ('lifecycle_order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cycle_year', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('full_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('name_key', models.CharField(blank=True, max_length=255)),
                ('person_group_key', models.CharField(blank=True, db_index=True, max_length=255)),
                ('identity_confidence', models.CharField(blank=True, max_length=120)),
                ('dob', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=40)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('cadre', models.CharField(blank=True, db_index=True, max_length=150)),
                ('cadre_group', models.CharField(blank=True, max_length=120)),
                ('profession_speciality_raw', models.CharField(blank=True, max_length=255)),
                ('formal_qualification', models.CharField(blank=True, max_length=255)),
                ('registration_no', models.CharField(blank=True, db_index=True, max_length=100)),
                ('practitioner_no', models.CharField(blank=True, db_index=True, max_length=100)),
                ('registration_link_key', models.CharField(blank=True, max_length=120)),
                ('institution', models.CharField(blank=True, db_index=True, max_length=255)),
                ('facility', models.CharField(blank=True, db_index=True, max_length=255)),
                ('province', models.CharField(blank=True, db_index=True, max_length=120)),
                ('organization_type', models.CharField(blank=True, max_length=160)),
                ('nationality_group', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('include_in_official_totals', models.BooleanField(default=True)),
                ('data_quality_flags', models.TextField(blank=True)),
                ('completeness_score', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('record_quality', models.CharField(blank=True, db_index=True, max_length=80)),
                ('source_workbook', models.CharField(blank=True, max_length=255)),
                ('source_sheet', models.CharField(blank=True, max_length=255)),
                ('source_row', models.PositiveIntegerField(blank=True, null=True)),
                ('source_lineage', models.CharField(blank=True, max_length=255)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_facts', to='dashboard.nursinganalyticssnapshot')),
            ],
            options={
                'ordering': ['cycle_year', 'record_id'],
                'unique_together': {('snapshot', 'record_id')},
            },
        ),
        migrations.CreateModel(
            name='NursingPractitionerIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practitioner_group_id', models.CharField(max_length=80)),
                ('person_group_key', models.CharField(blank=True, db_index=True, max_length=255)),
                ('representative_name', models.CharField(blank=True, max_length=255)),
                ('identity_confidence', models.CharField(blank=True, max_length=120)),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('stages_present', models.CharField(blank=True, max_length=255)),
                ('has_provisional', models.BooleanField(default=False)),
                ('has_full_licence', models.BooleanField(default=False)),
                ('has_atp', models.BooleanField(default=False)),
                ('first_year', models.PositiveIntegerField(blank=True, null=True)),
                ('latest_year', models.PositiveIntegerField(blank=True, null=True)),
                ('latest_atp_year', models.PositiveIntegerField(blank=True, null=True)),
                ('latest_cadre', models.CharField(blank=True, max_length=150)),
                ('latest_facility', models.CharField(blank=True, max_length=255)),
                ('latest_province', models.CharField(blank=True, max_length=120)),
                ('registration_nos', models.TextField(blank=True)),
                ('practitioner_nos', models.TextField(blank=True)),
                ('dq_flag_count', models.PositiveIntegerField(default=0)),
                ('needs_manual_review', models.BooleanField(default=False)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practitioner_index_rows', to='dashboard.nursinganalyticssnapshot')),
            ],
            options={
                'ordering': ['representative_name', 'practitioner_group_id'],
                'unique_together': {('snapshot', 'practitioner_group_id')},
            },
        ),
        migrations.CreateModel(
            name='NursingStageYearMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('provisional_licence_count', models.PositiveIntegerField(default=0)),
                ('full_licence_count', models.PositiveIntegerField(default=0)),
                ('authority_to_practice_count', models.PositiveIntegerField(default=0)),
                ('grand_total', models.PositiveIntegerField(default=0)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_year_metrics', to='dashboard.nursinganalyticssnapshot')),
            ],
            options={
                'ordering': ['year'],
                'unique_together': {('snapshot', 'year')},
            },
        ),
        migrations.CreateModel(
            name='NursingCadreStageMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadre', models.CharField(db_index=True, max_length=150)),
                ('cadre_group', models.CharField(blank=True, max_length=120)),
                ('provisional_licence_count', models.PositiveIntegerField(default=0)),
                ('full_licence_count', models.PositiveIntegerField(default=0)),
                ('authority_to_practice_count', models.PositiveIntegerField(default=0)),
                ('grand_total', models.PositiveIntegerField(default=0)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cadre_stage_metrics', to='dashboard.nursinganalyticssnapshot')),
            ],
            options={
                'ordering': ['-grand_total', 'cadre'],
                'unique_together': {('snapshot', 'cadre', 'cadre_group')},
            },
        ),
        migrations.CreateModel(
            name='NursingFacilityCadreYearMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(db_index=True, max_length=255)),
                ('province', models.CharField(blank=True, db_index=True, max_length=120)),
                ('organization_type', models.CharField(blank=True, max_length=160)),
                ('cadre', models.CharField(blank=True, db_index=True, max_length=150)),
                ('year', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('year_label', models.CharField(blank=True, max_length=40)),
                ('count', models.PositiveIntegerField(default=0)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_cadre_year_metrics', to='dashboard.nursinganalyticssnapshot')),
            ],
            options={
                'ordering': ['facility', 'cadre', 'year_label'],
            },
        ),
        migrations.CreateModel(
            name='NursingInstitutionCadreYearMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(db_index=True, max_length=255)),
                ('lifecycle_stage', models.CharField(blank=True, db_index=True, max_length=80)),
                ('cadre', models.CharField(blank=True, db_index=True, max_length=150)),
                ('year', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('year_label', models.CharField(blank=True, max_length=40)),
                ('count', models.PositiveIntegerField(default=0)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_cadre_year_metrics', to='dashboard.nursinganalyticssnapshot')),
            ],
            options={
                'ordering': ['institution', 'lifecycle_stage', 'cadre', 'year_label'],
            },
        ),
        migrations.CreateModel(
            name='NursingProvinceYearMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(db_index=True, max_length=120)),
                ('year', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('year_label', models.CharField(blank=True, max_length=40)),
                ('count', models.PositiveIntegerField(default=0)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='province_year_metrics', to='dashboard.nursinganalyticssnapshot')),
            ],
            options={
                'ordering': ['province', 'year_label'],
            },
        ),
        migrations.CreateModel(
            name='NursingDataQualityMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifecycle_stage', models.CharField(db_index=True, max_length=80)),
                ('high_count', models.PositiveIntegerField(default=0)),
                ('medium_count', models.PositiveIntegerField(default=0)),
                ('needs_review_count', models.PositiveIntegerField(default=0)),
                ('grand_total', models.PositiveIntegerField(default=0)),
                ('needs_review_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_quality_metrics', to='dashboard.nursinganalyticssnapshot')),
            ],
            options={
                'ordering': ['lifecycle_stage'],
                'unique_together': {('snapshot', 'lifecycle_stage')},
            },
        ),
        migrations.CreateModel(
            name='NursingStandardsFieldMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_type', models.CharField(choices=[('platform', 'Platform Field Map'), ('fhir_nhwa', 'FHIR / NHWA Map')], max_length=30)),
                ('platform_field', models.CharField(blank=True, max_length=255)),
                ('unified_field', models.CharField(db_index=True, max_length=255)),
                ('used_for', models.TextField(blank=True)),
                ('data_quality_rule', models.TextField(blank=True)),
                ('fhir_mapping', models.TextField(blank=True)),
                ('nhwa_dimension', models.TextField(blank=True)),
                ('implementation_note', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standards_field_maps', to='dashboard.nursinganalyticssnapshot')),
            ],
            options={
                'ordering': ['map_type', 'unified_field'],
            },
        ),
        migrations.CreateModel(
            name='NursingInstitutionAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(db_index=True, max_length=255)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('dhis2_org_unit_id', models.CharField(blank=True, max_length=120)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_aliases', to='dashboard.nursinganalyticssnapshot')),
                ('verified_institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nursing_analytics_aliases', to='workforce.traininginstitution')),
            ],
            options={
                'ordering': ['normalized_name'],
                'unique_together': {('snapshot', 'raw_name')},
            },
        ),
        migrations.CreateModel(
            name='NursingFacilityAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(db_index=True, max_length=255)),
                ('province', models.CharField(blank=True, max_length=120)),
                ('organization_type', models.CharField(blank=True, max_length=160)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('dhis2_org_unit_id', models.CharField(blank=True, max_length=120)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_aliases', to='dashboard.nursinganalyticssnapshot')),
                ('verified_facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nursing_analytics_aliases', to='workforce.facility')),
            ],
            options={
                'ordering': ['normalized_name'],
                'unique_together': {('snapshot', 'raw_name', 'province', 'organization_type')},
            },
        ),
        migrations.AddConstraint(
            model_name='nursinganalyticssnapshot',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_nursing_analytics_snapshot'),
        ),
        migrations.AddIndex(
            model_name='nursinganalyticssnapshot',
            index=models.Index(fields=['source_file_hash'], name='dashboard_nu_source__0ad048_idx'),
        ),
        migrations.AddIndex(
            model_name='nursinganalyticssnapshot',
            index=models.Index(fields=['is_active', 'created_at'], name='dashboard_nu_is_acti_0925f0_idx'),
        ),
        migrations.AddIndex(
            model_name='nursinglifecyclefact',
            index=models.Index(fields=['snapshot', 'lifecycle_stage', 'cycle_year'], name='dashboard_nu_snapsho_2c0382_idx'),
        ),
        migrations.AddIndex(
            model_name='nursinglifecyclefact',
            index=models.Index(fields=['snapshot', 'cadre'], name='dashboard_nu_snapsho_5ab018_idx'),
        ),
        migrations.AddIndex(
            model_name='nursinglifecyclefact',
            index=models.Index(fields=['snapshot', 'province'], name='dashboard_nu_snapsho_a5039c_idx'),
        ),
        migrations.AddIndex(
            model_name='nursinglifecyclefact',
            index=models.Index(fields=['snapshot', 'person_group_key'], name='dashboard_nu_snapsho_1db348_idx'),
        ),
        migrations.AddIndex(
            model_name='nursinglifecyclefact',
            index=models.Index(fields=['snapshot', 'record_quality'], name='dashboard_nu_snapsho_5eed0f_idx'),
        ),
        migrations.AddIndex(
            model_name='nursinglifecyclefact',
            index=models.Index(fields=['snapshot', 'facility'], name='dashboard_nu_snapsho_74e571_idx'),
        ),
        migrations.AddIndex(
            model_name='nursinglifecyclefact',
            index=models.Index(fields=['snapshot', 'institution'], name='dashboard_nu_snapsho_a7c7bf_idx'),
        ),
        migrations.AddIndex(
            model_name='nursingpractitionerindex',
            index=models.Index(fields=['snapshot', 'person_group_key'], name='dashboard_nu_snapsho_dac9d6_idx'),
        ),
        migrations.AddIndex(
            model_name='nursingpractitionerindex',
            index=models.Index(fields=['snapshot', 'latest_year'], name='dashboard_nu_snapsho_c77b5c_idx'),
        ),
        migrations.AddIndex(
            model_name='nursingstageyearmetric',
            index=models.Index(fields=['snapshot', 'year'], name='dashboard_nu_snapsho_93f0b6_idx'),
        ),
        migrations.AddIndex(
            model_name='nursingcadrestagemetric',
            index=models.Index(fields=['snapshot', 'cadre'], name='dashboard_nu_snapsho_ad15c4_idx'),
        ),
        migrations.AddIndex(
            model_name='nursingfacilitycadreyearmetric',
            index=models.Index(fields=['snapshot', 'facility'], name='dashboard_nu_snapsho_8d8220_idx'),
        ),
        migrations.AddIndex(
            model_name='nursingfacilitycadreyearmetric',
            index=models.Index(fields=['snapshot', 'province'], name='dashboard_nu_snapsho_29e41e_idx'),
        ),
        migrations.AddIndex(
            model_name='nursingfacilitycadreyearmetric',
            index=models.Index(fields=['snapshot', 'cadre', 'year'], name='dashboard_nu_snapsho_856c52_idx'),
        ),
        migrations.AddIndex(
            model_name='nursinginstitutioncadreyearmetric',
            index=models.Index(fields=['snapshot', 'institution'], name='dashboard_nu_snapsho_feb4a1_idx'),
        ),
        migrations.AddIndex(
            model_name='nursinginstitutioncadreyearmetric',
            index=models.Index(fields=['snapshot', 'lifecycle_stage'], name='dashboard_nu_snapsho_a1887a_idx'),
        ),
        migrations.AddIndex(
            model_name='nursinginstitutioncadreyearmetric',
            index=models.Index(fields=['snapshot', 'cadre', 'year'], name='dashboard_nu_snapsho_95ed19_idx'),
        ),
        migrations.AddIndex(
            model_name='nursingprovinceyearmetric',
            index=models.Index(fields=['snapshot', 'province'], name='dashboard_nu_snapsho_2f146b_idx'),
        ),
        migrations.AddIndex(
            model_name='nursingprovinceyearmetric',
            index=models.Index(fields=['snapshot', 'year'], name='dashboard_nu_snapsho_88c5a1_idx'),
        ),
        migrations.AddIndex(
            model_name='nursingdataqualitymetric',
            index=models.Index(fields=['snapshot', 'lifecycle_stage'], name='dashboard_nu_snapsho_fe5e91_idx'),
        ),
        migrations.AddIndex(
            model_name='nursingstandardsfieldmap',
            index=models.Index(fields=['snapshot', 'map_type'], name='dashboard_nu_snapsho_92e8d3_idx'),
        ),
        migrations.AddIndex(
            model_name='nursingstandardsfieldmap',
            index=models.Index(fields=['snapshot', 'unified_field'], name='dashboard_nu_snapsho_949236_idx'),
        ),
        migrations.AddIndex(
            model_name='nursinginstitutionalias',
            index=models.Index(fields=['snapshot', 'normalized_name'], name='dashboard_nu_snapsho_395cb8_idx'),
        ),
        migrations.AddIndex(
            model_name='nursinginstitutionalias',
            index=models.Index(fields=['snapshot', 'status'], name='dashboard_nu_snapsho_b45eeb_idx'),
        ),
        migrations.AddIndex(
            model_name='nursingfacilityalias',
            index=models.Index(fields=['snapshot', 'normalized_name'], name='dashboard_nu_snapsho_84a833_idx'),
        ),
        migrations.AddIndex(
            model_name='nursingfacilityalias',
            index=models.Index(fields=['snapshot', 'province'], name='dashboard_nu_snapsho_1d43de_idx'),
        ),
        migrations.AddIndex(
            model_name='nursingfacilityalias',
            index=models.Index(fields=['snapshot', 'status'], name='dashboard_nu_snapsho_0811bb_idx'),
        ),
    ]
