# Generated by Django 5.1 on 2026-05-28 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_normalize_nursing_analytics_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nursingstageyearmetric',
            options={'ordering': ['year', 'year_label']},
        ),
        migrations.AlterUniqueTogether(
            name='nursingstageyearmetric',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='nursingstageyearmetric',
            name='year_label',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='nursingstageyearmetric',
            name='year',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='nursingstageyearmetric',
            unique_together={('snapshot', 'year', 'year_label')},
        ),
    ]
