# Generated by Django 5.1 on 2026-05-29 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_preserve_unknown_stage_year_metrics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('audience', models.CharField(choices=[('public', 'Public'), ('practitioner', 'Applicant / Practitioner'), ('staff', 'Staff')], default='public', max_length=30)),
                ('office_scope', models.CharField(choices=[('shared', 'Shared'), ('nursing', 'Nursing Council'), ('medical', 'Medical Board')], default='shared', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ category',
                'verbose_name_plural': 'FAQ categories',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['audience', 'office_scope', 'is_active'], name='dashboard_f_audienc_12ceb3_idx'), models.Index(fields=['display_order', 'name'], name='dashboard_f_display_ebe586_idx')],
            },
        ),
        migrations.CreateModel(
            name='ForumCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('description', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('staff', 'All Staff'), ('nursing_staff', 'Nursing Council Staff'), ('medical_staff', 'Medical Board Staff'), ('practitioner', 'All Practitioners'), ('registered_nurse', 'Registered Nurses'), ('provisional', 'Provisional Licence Holders'), ('full_applicant', 'Full-Licence Applicants'), ('full_approved', 'Full-Licence Approved')], default='public', max_length=40)),
                ('office_scope', models.CharField(choices=[('shared', 'Shared'), ('nursing', 'Nursing Council'), ('medical', 'Medical Board')], default='shared', max_length=30)),
                ('requires_moderation', models.BooleanField(default=True)),
                ('allow_public_posts', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Forum categories',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['visibility', 'office_scope', 'is_active'], name='dashboard_f_visibil_ce953b_idx'), models.Index(fields=['display_order', 'name'], name='dashboard_f_display_9fc460_idx')],
            },
        ),
        migrations.CreateModel(
            name='ForumTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(max_length=240)),
                ('public_author_name', models.CharField(blank=True, max_length=120)),
                ('public_author_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending Moderation'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('last_post_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_topics', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='dashboard.forumcategory')),
            ],
            options={
                'ordering': ['-is_pinned', '-last_post_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_author_name', models.CharField(blank=True, max_length=120)),
                ('public_author_email', models.EmailField(blank=True, max_length=254)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Moderation'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('moderation_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_posts', to=settings.AUTH_USER_MODEL)),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='dashboard.forumtopic')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('closed', 'Closed'), ('reopened', 'Reopened')], max_length=30)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.forumcategory')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderation_logs', to='dashboard.forumpost')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderation_logs', to='dashboard.forumtopic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MappedEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(db_index=True, max_length=255)),
                ('entity_type', models.CharField(choices=[('institution', 'Institution'), ('facility', 'Facility'), ('school', 'School'), ('hospital', 'Hospital'), ('pha', 'Provincial Health Authority'), ('private_clinic', 'Private Clinic'), ('other', 'Other')], max_length=40)),
                ('office_scope', models.CharField(choices=[('shared', 'Shared'), ('nursing', 'Nursing Council'), ('medical', 'Medical Board')], default='shared', max_length=30)),
                ('province', models.CharField(blank=True, db_index=True, max_length=120)),
                ('district', models.CharField(blank=True, max_length=120)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('google_place_id', models.CharField(blank=True, max_length=180)),
                ('dhis2_org_unit_id', models.CharField(blank=True, max_length=120)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('source_model', models.CharField(blank=True, max_length=120)),
                ('source_object_id', models.CharField(blank=True, max_length=80)),
                ('active_workforce_count', models.PositiveIntegerField(default=0)),
                ('cadre_summary', models.JSONField(blank=True, default=dict)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Mapped entities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MappedEntityAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(db_index=True, max_length=255)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='dashboard.mappedentity')),
            ],
            options={
                'ordering': ['normalized_name'],
            },
        ),
        migrations.CreateModel(
            name='MappedEntityVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, max_length=30)),
                ('new_status', models.CharField(max_length=30)),
                ('note', models.TextField(blank=True)),
                ('evidence_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_events', to='dashboard.mappedentity')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('keywords', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='dashboard.faqcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category__display_order', 'display_order', 'question'],
                'indexes': [models.Index(fields=['is_published', 'display_order'], name='dashboard_f_is_publ_a999d8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='forumtopic',
            index=models.Index(fields=['category', 'status', 'is_pinned'], name='dashboard_f_categor_2f23db_idx'),
        ),
        migrations.AddIndex(
            model_name='forumtopic',
            index=models.Index(fields=['last_post_at', 'created_at'], name='dashboard_f_last_po_4622fd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='forumtopic',
            unique_together={('category', 'slug')},
        ),
        migrations.AddIndex(
            model_name='forumpost',
            index=models.Index(fields=['topic', 'status', 'created_at'], name='dashboard_f_topic_i_8a3cf8_idx'),
        ),
        migrations.AddIndex(
            model_name='forummoderationlog',
            index=models.Index(fields=['action', 'created_at'], name='dashboard_f_action_befb54_idx'),
        ),
        migrations.AddIndex(
            model_name='mappedentity',
            index=models.Index(fields=['office_scope', 'entity_type'], name='dashboard_m_office__eae0f5_idx'),
        ),
        migrations.AddIndex(
            model_name='mappedentity',
            index=models.Index(fields=['province', 'entity_type'], name='dashboard_m_provinc_5ed913_idx'),
        ),
        migrations.AddIndex(
            model_name='mappedentity',
            index=models.Index(fields=['verification_status', 'is_active'], name='dashboard_m_verific_a0b676_idx'),
        ),
        migrations.AddIndex(
            model_name='mappedentity',
            index=models.Index(fields=['latitude', 'longitude'], name='dashboard_m_latitud_8ae8da_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mappedentity',
            unique_together={('normalized_name', 'entity_type', 'office_scope', 'province')},
        ),
        migrations.AddIndex(
            model_name='mappedentityalias',
            index=models.Index(fields=['normalized_name', 'status'], name='dashboard_m_normali_6b6f9b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mappedentityalias',
            unique_together={('entity', 'raw_name')},
        ),
        migrations.AddIndex(
            model_name='mappedentityverification',
            index=models.Index(fields=['new_status', 'created_at'], name='dashboard_m_new_sta_fd62b7_idx'),
        ),
    ]
