# Generated by Django 5.1 on 2026-05-31 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dashboard', '0010_faqcategory_forumcategory_forumtopic_forumpost_and_more'),
        ('workforce', '0028_alter_practicinglicenserecord_record_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='payer_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_receipt_payers', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='payer_linked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='payer_match_confidence',
            field=models.CharField(choices=[('unlinked', 'Unlinked'), ('application', 'Application Link'), ('account', 'Account Link'), ('receipt_number', 'Receipt Number Match'), ('practitioner_number', 'Practitioner Number Match'), ('name_date_amount', 'Name / Date / Amount Match'), ('ambiguous', 'Ambiguous Match')], db_index=True, default='unlinked', max_length=40),
        ),
        migrations.AddField(
            model_name='receipt',
            name='payer_match_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='payer_match_rule',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='receipt',
            name='payer_object_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['payer_content_type', 'payer_object_id'], name='dashboard_r_payer_c_370090_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['payer_match_confidence', 'status'], name='dashboard_r_payer_m_b49db8_idx'),
        ),
    ]
