# Generated by Django 5.1 on 2026-06-11 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_receipt_payer_content_type_receipt_payer_linked_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('assistant_kind', models.CharField(choices=[('public_helpdesk', 'Public Helpdesk'), ('staff_assistant', 'Staff Assistant')], max_length=40)),
                ('browser_session_key', models.CharField(blank=True, db_index=True, max_length=80)),
                ('scope', models.CharField(choices=[('public', 'Public'), ('all', 'All Regulatory Offices'), ('nursing', 'Nursing Council'), ('medical', 'Medical Board'), ('restricted', 'Restricted')], default='public', max_length=30)),
                ('role', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('last_question', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('last_sources', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AssistantMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistant_kind', models.CharField(choices=[('public_helpdesk', 'Public Helpdesk'), ('staff_assistant', 'Staff Assistant')], max_length=40)),
                ('browser_session_key', models.CharField(blank=True, db_index=True, max_length=80)),
                ('scope', models.CharField(choices=[('public', 'Public'), ('all', 'All Regulatory Offices'), ('nursing', 'Nursing Council'), ('medical', 'Medical Board'), ('restricted', 'Restricted')], default='public', max_length=30)),
                ('memory_kind', models.CharField(choices=[('recent_focus', 'Recent Focus'), ('preference', 'Preference'), ('workflow_context', 'Workflow Context')], default='recent_focus', max_length=40)),
                ('memory_key', models.CharField(max_length=120)),
                ('memory_text', models.TextField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dashboard.assistantconversation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistant_memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AssistantMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dashboard.assistantconversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='assistantconversation',
            index=models.Index(fields=['assistant_kind', 'scope', 'updated_at'], name='dashboard_a_assista_10f578_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantconversation',
            index=models.Index(fields=['user', 'assistant_kind', 'updated_at'], name='dashboard_a_user_id_2be43a_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantconversation',
            index=models.Index(fields=['browser_session_key', 'assistant_kind'], name='dashboard_a_browser_9c7ec9_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantmemory',
            index=models.Index(fields=['assistant_kind', 'scope', 'memory_kind'], name='dashboard_a_assista_2d1037_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantmemory',
            index=models.Index(fields=['user', 'assistant_kind'], name='dashboard_a_user_id_f2a0b1_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantmemory',
            index=models.Index(fields=['browser_session_key', 'assistant_kind'], name='dashboard_a_browser_e7d944_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assistantmemory',
            unique_together={('assistant_kind', 'user', 'browser_session_key', 'scope', 'memory_kind', 'memory_key')},
        ),
        migrations.AddIndex(
            model_name='assistantmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='dashboard_a_convers_69fcb2_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantmessage',
            index=models.Index(fields=['role', 'created_at'], name='dashboard_a_role_4595b0_idx'),
        ),
    ]
