# Generated by Django 5.1 on 2026-07-07 02:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_disciplinarycase_disciplinarycaseevent_and_more'),
        ('dashboard', '0012_assistantconversation_assistantmemory_and_more'),
        ('documents', '0004_alter_documentaccesspolicy_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NursingCouncilBoardMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('meeting_type', models.CharField(choices=[('ordinary', 'Ordinary Council Meeting'), ('special', 'Special Council Meeting'), ('emergency', 'Emergency Council Meeting'), ('committee_report', 'Committee Report Meeting')], default='ordinary', max_length=40)),
                ('scheduled_for', models.DateTimeField(db_index=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('meeting_mode', models.CharField(choices=[('in_person', 'In person'), ('hybrid', 'Hybrid'), ('virtual', 'Virtual')], default='hybrid', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('papers_issued', 'Papers Issued'), ('in_session', 'In Session'), ('minutes_draft', 'Draft Minutes'), ('confirmed', 'Minutes Confirmed'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=30)),
                ('quorum_required', models.PositiveSmallIntegerField(default=5)),
                ('papers_due_at', models.DateTimeField(blank=True, null=True)),
                ('agenda_lock_at', models.DateTimeField(blank=True, null=True)),
                ('public_summary', models.TextField(blank=True)),
                ('private_notes', models.TextField(blank=True)),
                ('minutes_summary', models.TextField(blank=True)),
                ('minutes_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chaired_nursing_board_meetings', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_nursing_board_meetings', to=settings.AUTH_USER_MODEL)),
                ('secretary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretary_nursing_board_meetings', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_for', 'title'],
            },
        ),
        migrations.CreateModel(
            name='NursingCouncilBoardAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_on_board', models.CharField(choices=[('chair', 'Chair'), ('deputy_chair', 'Deputy Chair'), ('member', 'Member'), ('secretary', 'Secretary'), ('observer', 'Observer')], default='member', max_length=30)),
                ('attendance_status', models.CharField(choices=[('expected', 'Expected'), ('present', 'Present'), ('apology', 'Apology'), ('absent', 'Absent'), ('recused', 'Recused')], db_index=True, default='expected', max_length=20)),
                ('conflict_declared', models.BooleanField(default=False)),
                ('conflict_note', models.TextField(blank=True)),
                ('recusal_required', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nursing_board_attendance_records', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='dashboard.nursingcouncilboardmeeting')),
            ],
            options={
                'ordering': ['meeting', 'role_on_board', 'member__last_name', 'member__first_name'],
            },
        ),
        migrations.CreateModel(
            name='NursingCouncilBoardAgendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('purpose', models.CharField(choices=[('decision', 'Decision'), ('approval', 'Approval'), ('discussion', 'Discussion'), ('noting', 'For Noting')], default='discussion', max_length=30)),
                ('category', models.CharField(choices=[('registration', 'Registration'), ('education', 'Education and Accreditation'), ('standards', 'Standards and Policy'), ('conduct', 'Conduct and Fitness to Practise'), ('finance', 'Finance and Fees'), ('risk', 'Risk and Assurance'), ('governance', 'Governance'), ('other', 'Other')], default='governance', max_length=30)),
                ('confidentiality', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('confidential', 'Confidential')], default='private', max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('recommendation', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('noted', 'Noted'), ('approved', 'Approved'), ('deferred', 'Deferred'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('presenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presented_nursing_board_items', to=settings.AUTH_USER_MODEL)),
                ('related_decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_agenda_items', to='complaints.regulatorydecisionrecord')),
                ('related_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_agenda_items', to='documents.document')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_items', to='dashboard.nursingcouncilboardmeeting')),
            ],
            options={
                'ordering': ['meeting', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NursingCouncilBoardActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='normal', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('deferred', 'Deferred'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_nursing_board_actions', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_nursing_board_actions', to=settings.AUTH_USER_MODEL)),
                ('source_decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_action_items', to='complaints.regulatorydecisionrecord')),
                ('agenda_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_items', to='dashboard.nursingcouncilboardagendaitem')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='dashboard.nursingcouncilboardmeeting')),
            ],
            options={
                'ordering': ['status', 'due_date', 'priority', 'title'],
            },
        ),
        migrations.CreateModel(
            name='NursingCouncilBoardPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('classification', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('confidential', 'Confidential')], default='private', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('issued', 'Issued to Board'), ('withdrawn', 'Withdrawn'), ('superseded', 'Superseded')], db_index=True, default='draft', max_length=20)),
                ('version_label', models.CharField(blank=True, max_length=40)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agenda_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='papers', to='dashboard.nursingcouncilboardagendaitem')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_papers', to='documents.document')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='dashboard.nursingcouncilboardmeeting')),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_nursing_board_papers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['meeting', 'agenda_item__order', 'title'],
            },
        ),
        migrations.AddIndex(
            model_name='nursingcouncilboardmeeting',
            index=models.Index(fields=['status', 'scheduled_for'], name='dashboard_n_status_72e9af_idx'),
        ),
        migrations.AddIndex(
            model_name='nursingcouncilboardmeeting',
            index=models.Index(fields=['meeting_type', 'scheduled_for'], name='dashboard_n_meeting_722df6_idx'),
        ),
        migrations.AddIndex(
            model_name='nursingcouncilboardattendance',
            index=models.Index(fields=['meeting', 'attendance_status'], name='dashboard_n_meeting_51c187_idx'),
        ),
        migrations.AddIndex(
            model_name='nursingcouncilboardattendance',
            index=models.Index(fields=['conflict_declared', 'recusal_required'], name='dashboard_n_conflic_00afc4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='nursingcouncilboardattendance',
            unique_together={('meeting', 'member')},
        ),
        migrations.AddIndex(
            model_name='nursingcouncilboardagendaitem',
            index=models.Index(fields=['meeting', 'category', 'status'], name='dashboard_n_meeting_719d18_idx'),
        ),
        migrations.AddIndex(
            model_name='nursingcouncilboardagendaitem',
            index=models.Index(fields=['confidentiality', 'status'], name='dashboard_n_confide_3103f3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='nursingcouncilboardagendaitem',
            unique_together={('meeting', 'order')},
        ),
        migrations.AddIndex(
            model_name='nursingcouncilboardactionitem',
            index=models.Index(fields=['meeting', 'status'], name='dashboard_n_meeting_c7254b_idx'),
        ),
        migrations.AddIndex(
            model_name='nursingcouncilboardactionitem',
            index=models.Index(fields=['owner', 'status'], name='dashboard_n_owner_i_b049dd_idx'),
        ),
        migrations.AddIndex(
            model_name='nursingcouncilboardactionitem',
            index=models.Index(fields=['priority', 'due_date'], name='dashboard_n_priorit_02fe93_idx'),
        ),
        migrations.AddIndex(
            model_name='nursingcouncilboardpaper',
            index=models.Index(fields=['meeting', 'status'], name='dashboard_n_meeting_ecb37c_idx'),
        ),
        migrations.AddIndex(
            model_name='nursingcouncilboardpaper',
            index=models.Index(fields=['classification', 'status'], name='dashboard_n_classif_9226e6_idx'),
        ),
    ]
