# Generated by Codex on 2026-07-10

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0013_nursingcouncilboardmeeting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistryArchiveRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('archive_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('object_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('source_model', models.CharField(db_index=True, max_length=120)),
                ('source_reference', models.CharField(blank=True, db_index=True, max_length=255)),
                ('source_label', models.CharField(blank=True, max_length=255)),
                ('scope', models.CharField(choices=[('all', 'All Regulatory Offices'), ('nursing', 'Nursing Council'), ('medical', 'Medical Board')], db_index=True, default='all', max_length=20)),
                ('record_year', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('latest_renewal_year', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('archive_reason', models.CharField(choices=[('old_age', 'Old age / retirement age'), ('lapsed_renewal', 'Lapsed renewal'), ('expired_licence', 'Expired licence'), ('deceased', 'Deceased'), ('retired', 'Retired'), ('inactive', 'Inactive'), ('manual_review', 'Manual review')], db_index=True, max_length=40)),
                ('archive_status', models.CharField(choices=[('archived', 'Archived'), ('review_required', 'Review required'), ('confirmed_deceased', 'Confirmed deceased'), ('confirmed_retired', 'Confirmed retired'), ('restored', 'Restored')], db_index=True, default='archived', max_length=30)),
                ('registration_no', models.CharField(blank=True, db_index=True, max_length=100)),
                ('practitioner_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('cadre', models.CharField(blank=True, db_index=True, max_length=150)),
                ('facility', models.CharField(blank=True, db_index=True, max_length=255)),
                ('province', models.CharField(blank=True, db_index=True, max_length=120)),
                ('excluded_from_active_totals', models.BooleanField(db_index=True, default=True)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-archived_at', 'source_label'],
                'indexes': [
                    models.Index(fields=['scope', 'archive_reason', 'archive_status'], name='dashboard_r_scope_13fe7e_idx'),
                    models.Index(fields=['scope', 'record_year'], name='dashboard_r_scope_81d573_idx'),
                    models.Index(fields=['scope', 'latest_renewal_year'], name='dashboard_r_scope_5463f6_idx'),
                    models.Index(fields=['content_type', 'object_id'], name='dashboard_r_content_dce2e4_idx'),
                    models.Index(fields=['excluded_from_active_totals', 'archive_status'], name='dashboard_r_exclude_63c852_idx'),
                ],
            },
        ),
    ]
