# Generated by Django 5.2.16 on 2026-07-23

import django.db.models.deletion
import uuid

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0014_registryarchiverecord"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformConnectivityState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(default="platform", max_length=40, unique=True)),
                ("mode", models.CharField(choices=[("online", "Online"), ("offline_lan", "Offline LAN"), ("degraded", "Degraded"), ("unknown", "Unknown")], db_index=True, default="unknown", max_length=30)),
                ("forced_offline", models.BooleanField(default=False)),
                ("sync_enabled", models.BooleanField(default=True)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("last_online_at", models.DateTimeField(blank=True, null=True)),
                ("last_offline_at", models.DateTimeField(blank=True, null=True)),
                ("last_successful_url", models.URLField(blank=True)),
                ("last_error", models.TextField(blank=True)),
                ("consecutive_successes", models.PositiveIntegerField(default=0)),
                ("consecutive_failures", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Platform connectivity state",
                "verbose_name_plural": "Platform connectivity state",
            },
        ),
        migrations.CreateModel(
            name="PlatformSyncOutboxItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("item_uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("sync_type", models.CharField(db_index=True, max_length=80)),
                ("destination", models.CharField(blank=True, db_index=True, max_length=120)),
                ("endpoint_url", models.URLField(blank=True)),
                ("http_method", models.CharField(choices=[("POST", "POST"), ("PUT", "PUT"), ("PATCH", "PATCH"), ("DELETE", "DELETE")], default="POST", max_length=10)),
                ("idempotency_key", models.CharField(blank=True, max_length=160, null=True, unique=True)),
                ("headers_json", models.JSONField(blank=True, default=dict)),
                ("payload_json", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("in_progress", "In Progress"), ("synced", "Synced"), ("failed", "Failed"), ("blocked", "Blocked"), ("cancelled", "Cancelled")], db_index=True, default="pending", max_length=30)),
                ("priority", models.PositiveSmallIntegerField(db_index=True, default=50)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=12)),
                ("next_attempt_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("locked_by", models.CharField(blank=True, max_length=120)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("response_status_code", models.PositiveIntegerField(blank=True, null=True)),
                ("response_body_excerpt", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="platform_sync_outbox_items", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["priority", "created_at"],
                "indexes": [
                    models.Index(fields=["status", "next_attempt_at", "priority"], name="dashboard_p_status_cf9024_idx"),
                    models.Index(fields=["sync_type", "destination"], name="dashboard_p_sync_ty_13b552_idx"),
                    models.Index(fields=["created_at"], name="dashboard_p_created_68c253_idx"),
                ],
            },
        ),
    ]
