# Generated by Django 5.2.16 on 2026-07-24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_platformconnectivitystate_platformsyncoutboxitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('helpful', 'Helpful'), ('needs_review', 'Needs expert review')], max_length=20)),
                ('feedback_text', models.TextField(blank=True)),
                ('redacted_feedback', models.TextField(blank=True)),
                ('review_status', models.CharField(choices=[('pending', 'Pending redaction and review'), ('approved', 'Approved redacted feedback'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('requires_redaction', models.BooleanField(default=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistant_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='dashboard.assistantmessage')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_assistant_feedback', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('assistant_message', 'submitted_by')},
            },
        ),
        migrations.AddIndex(
            model_name='assistantfeedback',
            index=models.Index(fields=['review_status', 'created_at'], name='dashboard_a_review__f87138_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantfeedback',
            index=models.Index(fields=['submitted_by', 'created_at'], name='dashboard_a_submitt_fab2d3_idx'),
        ),
    ]
