# Generated by Django 5.1 on 2026-04-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('registrar', 'Registrar'), ('nurse', 'Nurse'), ('chw', 'Community Health Worker'), ('doctor', 'Doctor'), ('student', 'Student'), ('reviewer', 'Reviewer'), ('viewer', 'Viewer')], default='viewer', max_length=20),
        ),
    ]
