# Generated by Django 5.1 on 2026-04-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('registrar', 'Registrar'), ('reviewer', 'Reviewer'), ('viewer', 'Viewer'), ('nurse', 'Nurse'), ('chw', 'Community Health Worker'), ('doctor', 'Doctor'), ('student', 'Student')], default='viewer', max_length=20),
        ),
    ]
