# Generated by Django 5.1 on 2026-04-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_national_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
