# Generated by Django 5.1 on 2026-04-21 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_registration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('registrar', 'Registrar'), ('reviewer', 'Reviewer'), ('viewer', 'Viewer'), ('nurse_aide', 'Nurse Aide'), ('nurse', 'Nurse'), ('chw', 'Community Health Worker'), ('doctor', 'Doctor'), ('student', 'Student')], default='viewer', max_length=20),
        ),
    ]
