# Generated by Codex on 2026-04-24

from django.db import migrations


def normalize_nullable_unique_fields(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    for field_name in ('license_number', 'registration_number', 'national_id'):
        User.objects.filter(**{field_name: ''}).update(**{field_name: None})


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0007_user_employee_details_alter_user_role'),
    ]

    operations = [
        migrations.RunPython(normalize_nullable_unique_fields, migrations.RunPython.noop),
    ]
