# Generated by Django 5.1 on 2026-04-24 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_normalize_nullable_unique_user_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='applicant_type',
            field=models.CharField(choices=[('national', 'National'), ('overseas', 'Overseas')], default='national', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='id_document_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/ids/'),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/passports/'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/users/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('registrar', 'Registrar'), ('reviewer', 'Reviewer'), ('viewer', 'Viewer'), ('nurse_aide', 'Nurse Aide'), ('nurse', 'Nurse'), ('chw', 'Community Health Worker'), ('doctor', 'Doctor'), ('graduand', 'Graduand')], default='viewer', max_length=20),
        ),
    ]
