# Generated by Codex on 2026-04-24

from django.db import migrations


def forwards(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(role='student').update(role='graduand')


def backwards(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(role='graduand').update(role='student')


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0009_user_applicant_type_user_id_document_image_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
