# Generated by Codex on 2026-05-07

import re
from django.db import migrations


def backfill_operational_access_requests(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    OperationalAccessRequest = apps.get_model('accounts', 'OperationalAccessRequest')
    Notification = apps.get_model('notifications', 'Notification')

    for notification in Notification.objects.filter(subject__startswith='Full portal access request from'):
        match = re.search(r'\(([^)]+)\)\s+requested elevated access for\s+([^.]+)', notification.message or '')
        if not match:
            continue
        username = match.group(1).strip()
        office_label = match.group(2).strip().lower()
        requester = User.objects.filter(username=username, role='reviewer').first()
        if not requester:
            continue
        if 'nursing' in office_label:
            office = 'nursing'
        elif 'medical' in office_label:
            office = 'medical'
        elif 'finance' in office_label:
            office = 'finance'
        else:
            office = 'general'
        OperationalAccessRequest.objects.get_or_create(
            user=requester,
            status='pending',
            defaults={
                'requested_office': office,
                'reason': 'Backfilled from earlier profile access request notification.',
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_operational_access_request'),
        ('notifications', '0003_enquirythread_enquirymessage'),
    ]

    operations = [
        migrations.RunPython(backfill_operational_access_requests, migrations.RunPython.noop),
    ]
