# Generated by Django 5.1 on 2026-05-07 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_backfill_operational_access_requests'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(choices=[('LOGIN_SUCCESS', 'Login success'), ('LOGIN_FAILED', 'Login failed'), ('LOGOUT', 'Logout'), ('MFA_CHALLENGE_CREATED', 'MFA challenge created'), ('MFA_VERIFIED', 'MFA verified'), ('MFA_FAILED', 'MFA failed'), ('MFA_REQUIRED', 'MFA required'), ('ACCESS_DENIED', 'Access denied')], db_index=True, max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('path', models.CharField(blank=True, max_length=500)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='accounts_se_action_1ce9e7_idx'), models.Index(fields=['user', 'action'], name='accounts_se_user_id_13b28a_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserMFAChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('login', 'Login verification')], default='login', max_length=20)),
                ('code_hash', models.CharField(max_length=255)),
                ('delivery_channel', models.CharField(default='email', max_length=20)),
                ('sent_to', models.EmailField(blank=True, max_length=254)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'purpose', 'verified_at'], name='accounts_us_user_id_cad5d8_idx'), models.Index(fields=['expires_at'], name='accounts_us_expires_cdc0f9_idx')],
            },
        ),
    ]
