# Generated by Django 5.1 on 2026-05-15 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_securityauditevent_usermfachallenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_profile_contact',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='postal_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='practice_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='practice_district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='practice_province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='primary_contact_method',
            field=models.CharField(choices=[('portal', 'Portal Messages'), ('email', 'Email'), ('phone', 'Phone')], default='portal', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='professional_bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='professional_memberships',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_visibility',
            field=models.CharField(choices=[('private', 'Private to My Account'), ('regulatory_staff', 'Visible to Regulatory Staff'), ('public_directory', 'Public Directory Profile')], default='regulatory_staff', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='qualification_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='secondary_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='show_email_on_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='show_phone_on_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='specialty_area',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='user',
            name='work_status',
            field=models.CharField(choices=[('practicing', 'Practicing / Active'), ('available', 'Available for Work'), ('on_leave', 'On Leave'), ('training', 'In Training'), ('not_practicing', 'Not Currently Practicing'), ('retired', 'Retired')], default='practicing', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='workplace_location',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='user',
            name='workplace_name',
            field=models.CharField(blank=True, max_length=180),
        ),
    ]
