# Generated by Django 5.1 on 2026-05-18 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_allow_profile_contact_user_job_title_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cadre_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='professional_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professional_user_accounts', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='user',
            name='professional_link_review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='professional_linked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='professional_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='professional_record_status',
            field=models.CharField(choices=[('unmatched', 'No Professional Record Linked'), ('pending_review', 'Pending Registrar Review'), ('linked', 'Linked to Professional Record'), ('deceased', 'Deceased')], db_index=True, default='unmatched', max_length=30),
        ),
    ]
