# Generated by Django 5.1 on 2026-05-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_user_cadre_name_user_middle_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityauditevent',
            name='action',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login success'), ('LOGIN_FAILED', 'Login failed'), ('LOGOUT', 'Logout'), ('MFA_CHALLENGE_CREATED', 'MFA challenge created'), ('MFA_VERIFIED', 'MFA verified'), ('MFA_FAILED', 'MFA failed'), ('MFA_REQUIRED', 'MFA required'), ('ACCESS_DENIED', 'Access denied'), ('MOBILE_LOGIN_SUCCESS', 'Mobile login success'), ('MOBILE_LOGIN_FAILED', 'Mobile login failed'), ('MOBILE_BOOTSTRAP_REQUEST', 'Mobile bootstrap request')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('registrar', 'Registrar'), ('reviewer', 'Reviewer'), ('viewer', 'Viewer'), ('nurse_aide', 'Nurse Aide'), ('nurse', 'Nurse'), ('chw', 'Community Health Worker'), ('doctor', 'Doctor'), ('graduand', 'Graduand'), ('mobile_collector', 'Mobile Collector')], default='viewer', max_length=20),
        ),
    ]
