# Generated by Django 5.1 on 2026-07-07 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_user_system_admin_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('registrar', 'Registrar'), ('reviewer', 'Reviewer'), ('board_member', 'Board Member'), ('viewer', 'Viewer'), ('nurse_aide', 'Nurse Aide'), ('nurse', 'Nurse'), ('chw', 'Community Health Worker'), ('doctor', 'Doctor'), ('graduand', 'Graduand'), ('mobile_collector', 'Mobile Collector')], default='viewer', max_length=20),
        ),
    ]
