# Generated by Django 5.1 on 2026-05-19 14:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_alter_documentaccesspolicy_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_uuid', models.CharField(max_length=100, unique=True)),
                ('device_name', models.CharField(blank=True, max_length=255)),
                ('platform', models.CharField(default='android', max_length=50)),
                ('app_version', models.CharField(blank=True, max_length=50)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('risk_status', models.CharField(default='normal', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MobileLocalAccountRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_account_uuid', models.CharField(max_length=100, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('requested_role', models.CharField(max_length=100)),
                ('requested_cadre', models.CharField(blank=True, max_length=100)),
                ('office_scope', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DISABLED', 'Disabled')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mobile_intake.mobiledevice')),
                ('linked_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobile_account_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MobileSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('local_draft_id', models.CharField(max_length=100)),
                ('local_version', models.PositiveIntegerField(default=1)),
                ('office_scope', models.CharField(max_length=50)),
                ('form_code', models.CharField(max_length=50)),
                ('schema_version', models.CharField(max_length=50)),
                ('payload_json', models.JSONField(default=dict)),
                ('normalized_payload_json', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('VALIDATING', 'Validating'), ('DUPLICATE_RISK', 'Duplicate Risk'), ('NEEDS_REVIEW', 'Needs Review'), ('NEEDS_CORRECTION', 'Needs Correction'), ('REJECTED', 'Rejected'), ('ACCEPTED', 'Accepted'), ('PROMOTED', 'Promoted'), ('FAILED', 'Failed'), ('SUPERSEDED', 'Superseded')], default='RECEIVED', max_length=30)),
                ('validation_errors', models.JSONField(default=list)),
                ('duplicate_score', models.FloatField(blank=True, null=True)),
                ('duplicate_summary', models.JSONField(default=dict)),
                ('review_notes', models.TextField(blank=True)),
                ('correction_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('promoted_object_type', models.CharField(blank=True, max_length=100)),
                ('promoted_object_id', models.CharField(blank=True, max_length=100)),
                ('created_offline_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mobile_intake.mobiledevice')),
                ('local_account_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mobile_intake.mobilelocalaccountrequest')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='MobilePromotionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(max_length=100)),
                ('target_id', models.CharField(max_length=100)),
                ('action', models.CharField(default='promoted', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('promoted_at', models.DateTimeField(auto_now_add=True)),
                ('promoted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_links', to='mobile_intake.mobilesubmission')),
            ],
            options={
                'ordering': ['-promoted_at'],
            },
        ),
        migrations.CreateModel(
            name='MobileSubmissionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_attachment_uuid', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='mobile_intake/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveIntegerField()),
                ('sha256_checksum', models.CharField(max_length=64)),
                ('document_type', models.CharField(max_length=100)),
                ('office_scope', models.CharField(max_length=50)),
                ('ocr_status', models.CharField(default='PENDING', max_length=50)),
                ('upload_status', models.CharField(default='RECEIVED', max_length=50)),
                ('created_offline_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('repository_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.document')),
                ('repository_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.documentversion')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mobile_intake.mobilesubmission')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='MobileSubmissionStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=50)),
                ('new_status', models.CharField(max_length=50)),
                ('note', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='mobile_intake.mobilesubmission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MobileSyncEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('status_before', models.CharField(blank=True, max_length=50)),
                ('status_after', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mobile_intake.mobiledevice')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_events', to='mobile_intake.mobilesubmission')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MobileFormSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_code', models.CharField(max_length=50)),
                ('form_name', models.CharField(max_length=255)),
                ('office_scope', models.CharField(max_length=50)),
                ('schema_version', models.CharField(max_length=50)),
                ('json_schema', models.JSONField(default=dict)),
                ('ui_schema', models.JSONField(default=dict)),
                ('required_fields', models.JSONField(default=list)),
                ('attachment_requirements', models.JSONField(default=list)),
                ('validation_rules', models.JSONField(default=dict)),
                ('is_enabled', models.BooleanField(default=True)),
                ('enabled_for_roles', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['office_scope', 'form_code', '-schema_version'],
                'indexes': [models.Index(fields=['office_scope', 'form_code', 'is_enabled'], name='mobile_inta_office__6a56bd_idx')],
                'unique_together': {('form_code', 'office_scope', 'schema_version')},
            },
        ),
        migrations.AddIndex(
            model_name='mobilelocalaccountrequest',
            index=models.Index(fields=['office_scope', 'status'], name='mobile_inta_office__be7f90_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilelocalaccountrequest',
            index=models.Index(fields=['username'], name='mobile_inta_usernam_1e6970_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilesubmission',
            index=models.Index(fields=['office_scope', 'status'], name='mobile_inta_office__ef08df_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilesubmission',
            index=models.Index(fields=['form_code', 'schema_version'], name='mobile_inta_form_co_717d53_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilesubmission',
            index=models.Index(fields=['local_draft_id', 'local_version'], name='mobile_inta_local_d_d9cc04_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilesubmission',
            index=models.Index(fields=['received_at'], name='mobile_inta_receive_bdf2f3_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilepromotionlink',
            index=models.Index(fields=['target_type', 'target_id'], name='mobile_inta_target__32d992_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilepromotionlink',
            index=models.Index(fields=['submission', 'target_type'], name='mobile_inta_submiss_0f63b7_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilesubmissionattachment',
            index=models.Index(fields=['office_scope', 'document_type'], name='mobile_inta_office__ad3ae5_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilesubmissionattachment',
            index=models.Index(fields=['sha256_checksum'], name='mobile_inta_sha256__c51ca8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mobilesubmissionattachment',
            unique_together={('submission', 'local_attachment_uuid')},
        ),
        migrations.AddIndex(
            model_name='mobilesubmissionstatushistory',
            index=models.Index(fields=['submission', 'new_status'], name='mobile_inta_submiss_e0c2d2_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilesyncevent',
            index=models.Index(fields=['event_type', 'created_at'], name='mobile_inta_event_t_d3baad_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilesyncevent',
            index=models.Index(fields=['submission', 'created_at'], name='mobile_inta_submiss_9ed792_idx'),
        ),
    ]
