# Generated by Django 5.1 on 2026-06-01 05:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0008_enquirymessageattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('case_number', models.CharField(blank=True, editable=False, max_length=40, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('office_scope', models.CharField(choices=[('general', 'General Registry'), ('nursing', 'Nursing Council'), ('medical', 'Medical Board')], db_index=True, default='general', max_length=20)),
                ('case_type', models.CharField(choices=[('complaint', 'Complaint'), ('incident', 'Incident'), ('professional_conduct', 'Professional conduct'), ('licensing', 'Registration or licensing'), ('facility', 'Facility or employer'), ('training_institution', 'Training institution'), ('payment', 'Payment or receipt'), ('data_privacy', 'Data privacy'), ('service_quality', 'Service quality'), ('other', 'Other')], db_index=True, default='complaint', max_length=40)),
                ('source', models.CharField(choices=[('public_portal', 'Public portal'), ('staff_entry', 'Staff entry'), ('enquiry', 'Enquiry inbox'), ('email', 'Email'), ('phone', 'Phone'), ('walk_in', 'Walk-in'), ('mobile_intake', 'Mobile intake'), ('other', 'Other')], db_index=True, default='staff_entry', max_length=30)),
                ('status', models.CharField(choices=[('new', 'New'), ('triage', 'Triage'), ('assigned', 'Assigned'), ('investigating', 'Investigating'), ('awaiting_response', 'Awaiting response'), ('escalated', 'Escalated'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('withdrawn', 'Withdrawn')], db_index=True, default='new', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='normal', max_length=20)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=20)),
                ('incident_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('complainant_name', models.CharField(blank=True, max_length=255)),
                ('complainant_email', models.EmailField(blank=True, max_length=254)),
                ('complainant_phone', models.CharField(blank=True, max_length=50)),
                ('consent_to_contact', models.BooleanField(default=False)),
                ('subject_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('subject_name', models.CharField(blank=True, max_length=255)),
                ('subject_identifier', models.CharField(blank=True, max_length=120)),
                ('is_public_submission', models.BooleanField(db_index=True, default=False)),
                ('is_sensitive', models.BooleanField(default=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closure_summary', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaint_cases', to=settings.AUTH_USER_MODEL)),
                ('complainant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint_cases', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_complaint_cases', to=settings.AUTH_USER_MODEL)),
                ('source_enquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint_cases', to='notifications.enquirythread')),
                ('subject_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint_subject_cases', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintCaseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('intake', 'Intake'), ('note', 'Case note'), ('status_change', 'Status change'), ('assignment', 'Assignment'), ('triage', 'Triage'), ('escalation', 'Escalation'), ('public_response', 'Public response'), ('closure', 'Closure')], db_index=True, default='note', max_length=30)),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(blank=True, max_length=30)),
                ('body', models.TextField()),
                ('is_public_response', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='complaints.complaintcase')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint_case_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintCaseAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='complaint_cases/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='complaints.complaintcase')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint_case_attachments', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='complaints.complaintcaseevent')),
            ],
            options={
                'ordering': ['uploaded_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='complaintcase',
            index=models.Index(fields=['office_scope', 'status', 'priority'], name='complaints__office__66a787_idx'),
        ),
        migrations.AddIndex(
            model_name='complaintcase',
            index=models.Index(fields=['office_scope', 'risk_level'], name='complaints__office__cfbbdd_idx'),
        ),
        migrations.AddIndex(
            model_name='complaintcase',
            index=models.Index(fields=['assigned_to', 'status'], name='complaints__assigne_7cf7c9_idx'),
        ),
        migrations.AddIndex(
            model_name='complaintcase',
            index=models.Index(fields=['case_number'], name='complaints__case_nu_64ab66_idx'),
        ),
        migrations.AddIndex(
            model_name='complaintcase',
            index=models.Index(fields=['source', 'created_at'], name='complaints__source_aa7993_idx'),
        ),
        migrations.AddIndex(
            model_name='complaintcase',
            index=models.Index(fields=['subject_content_type', 'subject_object_id'], name='complaints__subject_232142_idx'),
        ),
        migrations.AddIndex(
            model_name='complaintcaseevent',
            index=models.Index(fields=['case', 'created_at'], name='complaints__case_id_aa6bc4_idx'),
        ),
        migrations.AddIndex(
            model_name='complaintcaseevent',
            index=models.Index(fields=['action_type', 'created_at'], name='complaints__action__30cef8_idx'),
        ),
    ]
