# Generated by Django 5.1 on 2026-06-01 06:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplinaryCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('discipline_number', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('office_scope', models.CharField(choices=[('general', 'General Registry'), ('nursing', 'Nursing Council'), ('medical', 'Medical Board')], db_index=True, default='general', max_length=20)),
                ('subject_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('subject_name', models.CharField(max_length=255)),
                ('subject_identifier', models.CharField(blank=True, max_length=120)),
                ('allegation_summary', models.TextField()),
                ('statutory_basis', models.TextField(blank=True)),
                ('stage', models.CharField(choices=[('intake', 'Intake'), ('preliminary_assessment', 'Preliminary assessment'), ('investigation', 'Investigation'), ('committee_review', 'Committee review'), ('notice_issued', 'Notice issued'), ('hearing', 'Hearing'), ('decision', 'Decision'), ('appeal_monitoring', 'Appeal / monitoring'), ('closed', 'Closed')], db_index=True, default='intake', max_length=40)),
                ('status', models.CharField(choices=[('open', 'Open'), ('on_hold', 'On hold'), ('awaiting_response', 'Awaiting response'), ('referred', 'Referred'), ('decided', 'Decided'), ('closed', 'Closed'), ('withdrawn', 'Withdrawn')], db_index=True, default='open', max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=20)),
                ('committee_reference', models.CharField(blank=True, max_length=160)),
                ('hearing_date', models.DateTimeField(blank=True, null=True)),
                ('notice_served_at', models.DateTimeField(blank=True, null=True)),
                ('response_due_at', models.DateTimeField(blank=True, null=True)),
                ('sanction_type', models.CharField(choices=[('none', 'No sanction'), ('warning', 'Warning'), ('conditions', 'Conditions on practice'), ('suspension', 'Suspension'), ('cancellation', 'Cancellation / removal'), ('referral', 'Referral to another authority'), ('other', 'Other')], db_index=True, default='none', max_length=30)),
                ('sanction_summary', models.TextField(blank=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_disciplinary_cases', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_disciplinary_cases', to=settings.AUTH_USER_MODEL)),
                ('source_complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinary_cases', to='complaints.complaintcase')),
                ('subject_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinary_subject_cases', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisciplinaryCaseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('intake', 'Intake'), ('note', 'Case note'), ('stage_change', 'Stage change'), ('assignment', 'Assignment'), ('notice', 'Notice'), ('evidence', 'Evidence'), ('hearing', 'Hearing'), ('decision', 'Decision'), ('appeal', 'Appeal'), ('closure', 'Closure')], db_index=True, default='note', max_length=30)),
                ('from_stage', models.CharField(blank=True, max_length=40)),
                ('to_stage', models.CharField(blank=True, max_length=40)),
                ('body', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='complaints.disciplinarycase')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinary_case_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DisciplinaryCaseAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='disciplinary_cases/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='complaints.disciplinarycase')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinary_case_attachments', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='complaints.disciplinarycaseevent')),
            ],
            options={
                'ordering': ['uploaded_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RegulatoryDecisionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('decision_number', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('office_scope', models.CharField(choices=[('general', 'General Registry'), ('nursing', 'Nursing Council'), ('medical', 'Medical Board')], db_index=True, default='general', max_length=20)),
                ('decision_type', models.CharField(choices=[('registration', 'Registration'), ('licence', 'Licence'), ('renewal', 'Renewal'), ('complaint', 'Complaint'), ('discipline', 'Discipline'), ('document', 'Document control'), ('data_quality', 'Data quality'), ('finance', 'Finance'), ('other', 'Other')], db_index=True, default='other', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Final'), ('superseded', 'Superseded'), ('withdrawn', 'Withdrawn')], db_index=True, default='draft', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('subject_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('subject_name', models.CharField(blank=True, max_length=255)),
                ('subject_identifier', models.CharField(blank=True, max_length=120)),
                ('decision_text', models.TextField()),
                ('rationale', models.TextField()),
                ('authority_reference', models.TextField(blank=True)),
                ('evidence_summary', models.TextField(blank=True)),
                ('conditions', models.TextField(blank=True)),
                ('appeal_rights', models.TextField(blank=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regulatory_decisions_created', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regulatory_decisions_made', to=settings.AUTH_USER_MODEL)),
                ('related_complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_records', to='complaints.complaintcase')),
                ('subject_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regulatory_decision_subjects', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-decided_at', '-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='disciplinarycase',
            name='decision_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinary_cases', to='complaints.regulatorydecisionrecord'),
        ),
        migrations.AddIndex(
            model_name='disciplinarycaseevent',
            index=models.Index(fields=['case', 'created_at'], name='complaints__case_id_112533_idx'),
        ),
        migrations.AddIndex(
            model_name='disciplinarycaseevent',
            index=models.Index(fields=['action_type', 'created_at'], name='complaints__action__9dc0a7_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatorydecisionrecord',
            index=models.Index(fields=['office_scope', 'decision_type', 'status'], name='complaints__office__d61028_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatorydecisionrecord',
            index=models.Index(fields=['decision_number'], name='complaints__decisio_083ea6_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatorydecisionrecord',
            index=models.Index(fields=['subject_content_type', 'subject_object_id'], name='complaints__subject_418be0_idx'),
        ),
        migrations.AddIndex(
            model_name='disciplinarycase',
            index=models.Index(fields=['office_scope', 'stage', 'status'], name='complaints__office__04ce57_idx'),
        ),
        migrations.AddIndex(
            model_name='disciplinarycase',
            index=models.Index(fields=['assigned_to', 'status'], name='complaints__assigne_493f8b_idx'),
        ),
        migrations.AddIndex(
            model_name='disciplinarycase',
            index=models.Index(fields=['severity', 'status'], name='complaints__severit_7bd0f6_idx'),
        ),
        migrations.AddIndex(
            model_name='disciplinarycase',
            index=models.Index(fields=['subject_content_type', 'subject_object_id'], name='complaints__subject_cbad8e_idx'),
        ),
    ]
