# Generated by Django 5.1 on 2026-05-04 04:41

import apps.documents.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('workforce', '0021_missingdatareview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_scope', models.CharField(choices=[('general', 'General Registry'), ('nursing', 'Nursing Council'), ('medical', 'Medical Board')], db_index=True, default='general', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived'), ('superseded', 'Superseded')], db_index=True, default='draft', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_record', models.BooleanField(default=False, help_text='Marks the document as an official managed record.')),
                ('retention_years', models.PositiveIntegerField(blank=True, null=True)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL)),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repository_documents', to='workforce.documenttype')),
                ('related_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-updated_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DocumentFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_scope', models.CharField(choices=[('general', 'General Registry'), ('nursing', 'Nursing Council'), ('medical', 'Medical Board')], db_index=True, default='general', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_document_folders', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='documents.documentfolder')),
            ],
            options={
                'ordering': ['office_scope', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAccessPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('admin', 'Admin'), ('registrar', 'Registrar'), ('reviewer', 'Reviewer'), ('viewer', 'Viewer'), ('nurse', 'Nurse'), ('doctor', 'Doctor'), ('chw', 'Community Health Worker'), ('graduand', 'Graduand'), ('nurse_aide', 'Nurse Aide')], db_index=True, max_length=20)),
                ('can_view', models.BooleanField(default=True)),
                ('can_download', models.BooleanField(default=True)),
                ('can_upload', models.BooleanField(default=False)),
                ('can_edit_metadata', models.BooleanField(default=False)),
                ('can_manage_permissions', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_policies', to='documents.document')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_access_policies', to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_policies', to='documents.documentfolder')),
            ],
            options={
                'ordering': ['role', 'user_id'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.documentfolder'),
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('file', models.FileField(upload_to=apps.documents.models.document_version_upload_to)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('file_size', models.BigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('extracted_text', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_document_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version_number', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('uploaded', 'Uploaded'), ('viewed', 'Viewed'), ('downloaded', 'Downloaded'), ('metadata_updated', 'Metadata Updated'), ('status_changed', 'Status Changed'), ('permission_changed', 'Permission Changed'), ('linked', 'Linked To Record'), ('ocr_processed', 'OCR Processed'), ('access_denied', 'Access Denied')], db_index=True, max_length=30)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='documents.document')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_audit_events', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='documents.documentversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='documentfolder',
            index=models.Index(fields=['office_scope', 'name'], name='documents_d_office__598cc9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentfolder',
            unique_together={('office_scope', 'parent', 'name')},
        ),
        migrations.AddIndex(
            model_name='documentaccesspolicy',
            index=models.Index(fields=['role'], name='documents_d_role_0f4b14_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['office_scope', 'status'], name='documents_d_office__142482_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['title'], name='documents_d_title_ccf306_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['related_content_type', 'related_object_id'], name='documents_d_related_f203de_idx'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['document', 'is_current'], name='documents_d_documen_a34803_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentversion',
            unique_together={('document', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='documentauditevent',
            index=models.Index(fields=['document', 'event_type'], name='documents_d_documen_fa21f8_idx'),
        ),
        migrations.AddIndex(
            model_name='documentauditevent',
            index=models.Index(fields=['created_at', 'event_type'], name='documents_d_created_c7d134_idx'),
        ),
    ]
