# Generated by Django 5.1 on 2026-06-01 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_documentaccesspolicy_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentauditevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('uploaded', 'Uploaded'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('viewed', 'Viewed'), ('downloaded', 'Downloaded'), ('metadata_updated', 'Metadata Updated'), ('status_changed', 'Status Changed'), ('permission_changed', 'Permission Changed'), ('linked', 'Linked To Record'), ('ocr_processed', 'OCR Processed'), ('access_denied', 'Access Denied')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='DocumentApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('revoked', 'Revoked')], db_index=True, max_length=20)),
                ('note', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_approvals', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='documents.document')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to='documents.documentversion')),
            ],
            options={
                'ordering': ['-approved_at'],
                'indexes': [models.Index(fields=['document', 'status'], name='documents_d_documen_37ada4_idx'), models.Index(fields=['approved_at', 'status'], name='documents_d_approve_0854ef_idx')],
            },
        ),
    ]
