# Generated by Django 5.1 on 2026-07-07 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_documentauditevent_event_type_documentapproval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentaccesspolicy',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('registrar', 'Registrar'), ('reviewer', 'Reviewer'), ('board_member', 'Board Member'), ('viewer', 'Viewer'), ('nurse', 'Nurse'), ('doctor', 'Doctor'), ('chw', 'Community Health Worker'), ('graduand', 'Graduand'), ('nurse_aide', 'Nurse Aide'), ('mobile_collector', 'Mobile Collector')], db_index=True, max_length=20),
        ),
    ]
