# Generated by Django 5.1 on 2026-05-25 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NHWAWebSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_sheet_name', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('max_row', models.PositiveIntegerField(default=0)),
                ('max_column', models.PositiveIntegerField(default=0)),
                ('editable', models.BooleanField(default=True)),
                ('purpose', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['workbook', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NHWACellTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinate', models.CharField(max_length=12)),
                ('row_index', models.PositiveIntegerField()),
                ('column_index', models.PositiveIntegerField()),
                ('column_letter', models.CharField(max_length=6)),
                ('initial_value', models.TextField(blank=True)),
                ('formula', models.TextField(blank=True)),
                ('fill_rgb', models.CharField(blank=True, max_length=12)),
                ('is_editable', models.BooleanField(default=False)),
                ('is_formula', models.BooleanField(default=False)),
                ('is_heading', models.BooleanField(default=False)),
                ('is_required', models.BooleanField(default=False)),
                ('number_format', models.CharField(blank=True, max_length=80)),
                ('style_json', models.JSONField(blank=True, default=dict)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cell_templates', to='nhwa_workbooks.nhwawebsheet')),
            ],
            options={
                'ordering': ['sheet', 'row_index', 'column_index'],
            },
        ),
        migrations.CreateModel(
            name='NHWAWebWorkbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_scope', models.CharField(choices=[('nursing', 'Nursing Council'), ('medical', 'Medical Board')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('source_title', models.CharField(blank=True, max_length=255)),
                ('source_version', models.CharField(blank=True, max_length=80)),
                ('reporting_year', models.PositiveIntegerField(default=2025)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('locked', 'Locked'), ('archived', 'Archived')], db_index=True, default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_nhwa_workbooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['office_scope', 'title'],
            },
        ),
        migrations.AddField(
            model_name='nhwawebsheet',
            name='workbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='nhwa_workbooks.nhwawebworkbook'),
        ),
        migrations.CreateModel(
            name='NHWAWorkbookAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('BOOTSTRAPPED', 'Bootstrapped'), ('CELL_UPDATED', 'Cell updated'), ('SHEET_SAVED', 'Sheet saved'), ('VIEWED', 'Viewed'), ('LOCKED', 'Locked'), ('UNLOCKED', 'Unlocked')], max_length=40)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='nhwa_workbooks.nhwawebsheet')),
                ('workbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='nhwa_workbooks.nhwawebworkbook')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NHWACellEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_nhwa_cells', to=settings.AUTH_USER_MODEL)),
                ('template', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entry', to='nhwa_workbooks.nhwacelltemplate')),
            ],
            options={
                'ordering': ['template__sheet', 'template__row_index', 'template__column_index'],
                'indexes': [models.Index(fields=['updated_at'], name='nhwa_workbo_updated_0c8964_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='nhwacelltemplate',
            index=models.Index(fields=['sheet', 'row_index', 'column_index'], name='nhwa_workbo_sheet_i_18570a_idx'),
        ),
        migrations.AddIndex(
            model_name='nhwacelltemplate',
            index=models.Index(fields=['sheet', 'is_editable'], name='nhwa_workbo_sheet_i_664342_idx'),
        ),
        migrations.AddIndex(
            model_name='nhwacelltemplate',
            index=models.Index(fields=['sheet', 'is_formula'], name='nhwa_workbo_sheet_i_08e1dd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='nhwacelltemplate',
            unique_together={('sheet', 'coordinate')},
        ),
        migrations.AddIndex(
            model_name='nhwawebworkbook',
            index=models.Index(fields=['office_scope', 'status'], name='nhwa_workbo_office__6da22b_idx'),
        ),
        migrations.AddIndex(
            model_name='nhwawebsheet',
            index=models.Index(fields=['source_sheet_name'], name='nhwa_workbo_source__feb019_idx'),
        ),
        migrations.AddIndex(
            model_name='nhwawebsheet',
            index=models.Index(fields=['editable'], name='nhwa_workbo_editabl_722d19_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='nhwawebsheet',
            unique_together={('workbook', 'source_sheet_name')},
        ),
        migrations.AddIndex(
            model_name='nhwaworkbookauditevent',
            index=models.Index(fields=['action', 'created_at'], name='nhwa_workbo_action_e4f0ee_idx'),
        ),
        migrations.AddIndex(
            model_name='nhwaworkbookauditevent',
            index=models.Index(fields=['workbook', 'created_at'], name='nhwa_workbo_workboo_9cd1be_idx'),
        ),
    ]
