# Generated by Django 5.1 on 2026-04-12 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='healthstudent',
            name='competency_statement_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='midwife',
            name='qualification_level',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='nursingprofessional',
            name='qualification_level',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='form_code',
            field=models.CharField(choices=[('NC1', 'NC1 - Provisional Licence'), ('NC2', 'NC2 - Full Licence (PNG)'), ('NC3', 'NC3 - Renewal of Licence'), ('NC5', 'NC5 - Full Registration (Overseas)'), ('NC8', 'NC8 - Temporary Licence'), ('G1', 'G1 - Graduate Checklist'), ('G4', 'G4 - Competency Nurse'), ('G5', 'G5 - Competency Midwife'), ('G6', 'G6 - Competency CHW'), ('OTHER', 'Other')], default='OTHER', max_length=10),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=30),
        ),
    ]
