# Generated by Django 5.1 on 2026-04-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0004_alter_communityhealthworker_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='notified_expiry',
            field=models.BooleanField(default=False),
        ),
    ]
