# Generated by Django 5.1 on 2026-04-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0005_application_notified_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='form_code',
            field=models.CharField(choices=[('NC1', 'NC1 - Provisional Licence'), ('NC2', 'NC2 - Full Licence (PNG)'), ('NC3', 'NC3 - Renewal of Licence'), ('NC5', 'NC5 - Full Registration (Overseas)'), ('NC8', 'NC8 - Temporary Licence'), ('G1', 'G1 - Graduate Checklist'), ('G4', 'G4 - Competency Nurse'), ('G5', 'G5 - Competency Midwife'), ('G6', 'G6 - Competency CHW'), ('G7', 'G7 - Final Graduate Submission'), ('OTHER', 'Other')], default='OTHER', max_length=10),
        ),
    ]
