# Generated by Django 5.1 on 2026-04-12 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0007_remove_application_notified_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursingprofessional',
            name='employee_details',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
