# Generated by Django 5.1 on 2026-04-13 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('workforce', '0008_nursingprofessional_employee_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='midwife',
            name='qualification_level',
        ),
        migrations.RemoveField(
            model_name='nursingprofessional',
            name='employee_details',
        ),
        migrations.AlterField(
            model_name='healthstudent',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workforce.traininginstitution'),
        ),
        migrations.AlterField(
            model_name='medicaldoctor',
            name='registration_number',
            field=models.CharField(blank=True, max_length=600, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='midwife',
            name='registration_number',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='nursingprofessional',
            name='registration_number',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='CPDRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('training_type', models.CharField(max_length=150)),
                ('provider', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField()),
                ('hours_credits', models.FloatField(default=0)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='cpd/')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workforce_cpdrecord', to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='PostingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('position_title', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workforce.facility')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='documents/')),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workforce.documenttype')),
            ],
        ),
    ]
