# Generated by Django 5.1 on 2026-04-16 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0009_remove_midwife_qualification_level_and_more'),
    ]

    operations = [
    ]
