# Generated by Django 5.1 on 2026-04-16 05:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('workforce', '0010_auto_20260416_1031'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('qualification_name', models.CharField(max_length=200)),
                ('completion_year', models.IntegerField(blank=True, null=True)),
                ('qualification_type', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='cadre',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='workforcesnapshot',
            options={},
        ),
        migrations.RenameField(
            model_name='application',
            old_name='rejected_date',
            new_name='expiry_date',
        ),
        migrations.RenameField(
            model_name='midwife',
            old_name='license_expiry',
            new_name='date_issued',
        ),
        migrations.RenameField(
            model_name='nursingprofessional',
            old_name='license_expiry',
            new_name='date_issued',
        ),
        migrations.RemoveField(
            model_name='application',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='communityhealthworker',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='communityhealthworker',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='communityhealthworker',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='cpdrecord',
            name='certificate_file',
        ),
        migrations.RemoveField(
            model_name='healthstudent',
            name='competency_statement_submitted',
        ),
        migrations.RemoveField(
            model_name='healthstudent',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='healthstudent',
            name='graduate_checklist_completed',
        ),
        migrations.RemoveField(
            model_name='healthstudent',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='medicaldoctor',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='medicaldoctor',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='medicaldoctor',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='medicaldoctor',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='midwife',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='midwife',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='midwife',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='midwife',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='nursingprofessional',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='nursingprofessional',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='nursingprofessional',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='nursingprofessional',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='professionaldocument',
            name='upload_date',
        ),
        migrations.RemoveField(
            model_name='professionaldocument',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='traininginstitution',
            name='accreditation_status',
        ),
        migrations.AddField(
            model_name='cadre',
            name='category',
            field=models.CharField(choices=[('nursing', 'Nursing'), ('midwifery', 'Midwifery'), ('medical', 'Medical'), ('chw', 'CHW'), ('other', 'Other')], default='nursing', max_length=50),
        ),
        migrations.AddField(
            model_name='communityhealthworker',
            name='cadre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workforce.cadre'),
        ),
        migrations.AddField(
            model_name='communityhealthworker',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='healthstudent',
            name='cadre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workforce.cadre'),
        ),
        migrations.AddField(
            model_name='healthstudent',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthstudent',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='healthstudent',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='healthstudent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='healthstudent',
            name='primary_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='healthstudent',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='medicaldoctor',
            name='date_issued',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicaldoctor',
            name='specialty',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='midwife',
            name='license_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='midwife',
            name='qualification_level',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='nursingprofessional',
            name='license_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postinghistory',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professionaldocument',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traininginstitution',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='form_code',
            field=models.CharField(choices=[('NC1', 'NC1 - Provisional'), ('NC2', 'NC2 - Full'), ('G1', 'Graduate'), ('GD', 'GD'), ('PG', 'PG')], max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='cadre',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='communityhealthworker',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='communityhealthworker',
            name='primary_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cpdrecord',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workforce_cpd_records', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='cpdrecord',
            name='provider',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='healthstudent',
            name='program',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='medicaldoctor',
            name='cadre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workforce.cadre'),
        ),
        migrations.AlterField(
            model_name='medicaldoctor',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='medicaldoctor',
            name='primary_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='medicaldoctor',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='midwife',
            name='cadre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workforce.cadre'),
        ),
        migrations.AlterField(
            model_name='midwife',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='midwife',
            name='primary_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='midwife',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='nursingprofessional',
            name='cadre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workforce.cadre'),
        ),
        migrations.AlterField(
            model_name='nursingprofessional',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='nursingprofessional',
            name='primary_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nursingprofessional',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='postinghistory',
            name='facility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workforce.facility'),
        ),
        migrations.AlterField(
            model_name='professionaldocument',
            name='document_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workforce.documenttype'),
        ),
        migrations.AlterField(
            model_name='traininginstitution',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='traininginstitution',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='workforcesnapshot',
            name='total_active_workers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workforcesnapshot',
            name='total_chw',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workforcesnapshot',
            name='total_doctors',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workforcesnapshot',
            name='total_midwives',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workforcesnapshot',
            name='total_nurses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['content_type', 'object_id'], name='workforce_a_content_a1897a_idx'),
        ),
        migrations.AddIndex(
            model_name='communityhealthworker',
            index=models.Index(fields=['registration_number'], name='workforce_c_registr_ef957f_idx'),
        ),
        migrations.AddIndex(
            model_name='communityhealthworker',
            index=models.Index(fields=['national_id'], name='workforce_c_nationa_b4cf72_idx'),
        ),
        migrations.AddIndex(
            model_name='cpdrecord',
            index=models.Index(fields=['content_type', 'object_id'], name='workforce_c_content_b2eb50_idx'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['name'], name='workforce_f_name_9c0736_idx'),
        ),
        migrations.AddIndex(
            model_name='healthstudent',
            index=models.Index(fields=['registration_number'], name='workforce_h_registr_c0ca17_idx'),
        ),
        migrations.AddIndex(
            model_name='healthstudent',
            index=models.Index(fields=['national_id'], name='workforce_h_nationa_4d8f09_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['province', 'district'], name='workforce_l_provinc_18e16f_idx'),
        ),
        migrations.AddIndex(
            model_name='medicaldoctor',
            index=models.Index(fields=['registration_number'], name='workforce_m_registr_3f0efb_idx'),
        ),
        migrations.AddIndex(
            model_name='medicaldoctor',
            index=models.Index(fields=['national_id'], name='workforce_m_nationa_adc943_idx'),
        ),
        migrations.AddIndex(
            model_name='midwife',
            index=models.Index(fields=['registration_number'], name='workforce_m_registr_862c41_idx'),
        ),
        migrations.AddIndex(
            model_name='midwife',
            index=models.Index(fields=['national_id'], name='workforce_m_nationa_5dc64c_idx'),
        ),
        migrations.AddIndex(
            model_name='nursingprofessional',
            index=models.Index(fields=['registration_number'], name='workforce_n_registr_169f49_idx'),
        ),
        migrations.AddIndex(
            model_name='nursingprofessional',
            index=models.Index(fields=['national_id'], name='workforce_n_nationa_9754d6_idx'),
        ),
        migrations.AddIndex(
            model_name='postinghistory',
            index=models.Index(fields=['content_type', 'object_id'], name='workforce_p_content_130293_idx'),
        ),
        migrations.AddIndex(
            model_name='professionaldocument',
            index=models.Index(fields=['content_type', 'object_id'], name='workforce_p_content_7f7a7e_idx'),
        ),
        migrations.AddField(
            model_name='qualification',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='qualification',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workforce.traininginstitution'),
        ),
        migrations.AddIndex(
            model_name='qualification',
            index=models.Index(fields=['content_type', 'object_id'], name='workforce_q_content_2735b7_idx'),
        ),
    ]
