# Generated by Django 5.1 on 2026-04-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0012_professionalphoto'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='communityhealthworker',
            name='workforce_c_nationa_b4cf72_idx',
        ),
        migrations.RemoveIndex(
            model_name='healthstudent',
            name='workforce_h_nationa_4d8f09_idx',
        ),
        migrations.RemoveIndex(
            model_name='medicaldoctor',
            name='workforce_m_nationa_adc943_idx',
        ),
        migrations.RemoveIndex(
            model_name='midwife',
            name='workforce_m_nationa_5dc64c_idx',
        ),
        migrations.RemoveIndex(
            model_name='nursingprofessional',
            name='workforce_n_nationa_9754d6_idx',
        ),
        migrations.RemoveField(
            model_name='communityhealthworker',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='healthstudent',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='medicaldoctor',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='midwife',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='nursingprofessional',
            name='national_id',
        ),
        migrations.AddField(
            model_name='communityhealthworker',
            name='registration_no',
            field=models.CharField(blank=True, db_column='Registration_No', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='healthstudent',
            name='registration_no',
            field=models.CharField(blank=True, db_column='Registration_No', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='medicaldoctor',
            name='registration_no',
            field=models.CharField(blank=True, db_column='Registration_No', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='midwife',
            name='registration_no',
            field=models.CharField(blank=True, db_column='Registration_No', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='nursingprofessional',
            name='registration_no',
            field=models.CharField(blank=True, db_column='Registration_No', max_length=50, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='communityhealthworker',
            index=models.Index(fields=['registration_no'], name='workforce_c_Registr_248546_idx'),
        ),
        migrations.AddIndex(
            model_name='healthstudent',
            index=models.Index(fields=['registration_no'], name='workforce_h_Registr_3c153a_idx'),
        ),
        migrations.AddIndex(
            model_name='medicaldoctor',
            index=models.Index(fields=['registration_no'], name='workforce_m_Registr_c1df63_idx'),
        ),
        migrations.AddIndex(
            model_name='midwife',
            index=models.Index(fields=['registration_no'], name='workforce_m_Registr_53e8e6_idx'),
        ),
        migrations.AddIndex(
            model_name='nursingprofessional',
            index=models.Index(fields=['registration_no'], name='workforce_n_Registr_399cff_idx'),
        ),
    ]
