# Generated by Django 5.1 on 2026-04-21 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0013_remove_communityhealthworker_workforce_c_nationa_b4cf72_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NurseAide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('registration_no', models.CharField(blank=True, db_column='Registration_No', max_length=50, null=True, unique=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('primary_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('training_level', models.CharField(blank=True, max_length=100)),
                ('employer', models.CharField(blank=True, max_length=150)),
                ('cadre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workforce.cadre')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['registration_number'], name='workforce_n_registr_4b4a0e_idx'), models.Index(fields=['registration_no'], name='workforce_n_Registr_c4c255_idx')],
            },
        ),
    ]
