# Generated by Django 5.1 on 2026-04-24 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0014_nurseaide'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthstudent',
            options={'verbose_name': 'Graduand', 'verbose_name_plural': 'Graduands'},
        ),
        migrations.RemoveIndex(
            model_name='healthstudent',
            name='workforce_h_registr_c0ca17_idx',
        ),
        migrations.RemoveIndex(
            model_name='healthstudent',
            name='workforce_h_Registr_3c153a_idx',
        ),
        migrations.AddField(
            model_name='communityhealthworker',
            name='applicant_type',
            field=models.CharField(choices=[('national', 'National'), ('overseas', 'Overseas')], default='national', max_length=20),
        ),
        migrations.AddField(
            model_name='communityhealthworker',
            name='id_document_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/ids/'),
        ),
        migrations.AddField(
            model_name='communityhealthworker',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/passports/'),
        ),
        migrations.AddField(
            model_name='healthstudent',
            name='applicant_type',
            field=models.CharField(choices=[('national', 'National'), ('overseas', 'Overseas')], default='national', max_length=20),
        ),
        migrations.AddField(
            model_name='healthstudent',
            name='id_document_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/ids/'),
        ),
        migrations.AddField(
            model_name='healthstudent',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/passports/'),
        ),
        migrations.AddField(
            model_name='medicaldoctor',
            name='applicant_type',
            field=models.CharField(choices=[('national', 'National'), ('overseas', 'Overseas')], default='national', max_length=20),
        ),
        migrations.AddField(
            model_name='medicaldoctor',
            name='id_document_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/ids/'),
        ),
        migrations.AddField(
            model_name='medicaldoctor',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/passports/'),
        ),
        migrations.AddField(
            model_name='midwife',
            name='applicant_type',
            field=models.CharField(choices=[('national', 'National'), ('overseas', 'Overseas')], default='national', max_length=20),
        ),
        migrations.AddField(
            model_name='midwife',
            name='id_document_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/ids/'),
        ),
        migrations.AddField(
            model_name='midwife',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/passports/'),
        ),
        migrations.AddField(
            model_name='nurseaide',
            name='applicant_type',
            field=models.CharField(choices=[('national', 'National'), ('overseas', 'Overseas')], default='national', max_length=20),
        ),
        migrations.AddField(
            model_name='nurseaide',
            name='id_document_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/ids/'),
        ),
        migrations.AddField(
            model_name='nurseaide',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/passports/'),
        ),
        migrations.AddField(
            model_name='nursingprofessional',
            name='applicant_type',
            field=models.CharField(choices=[('national', 'National'), ('overseas', 'Overseas')], default='national', max_length=20),
        ),
        migrations.AddField(
            model_name='nursingprofessional',
            name='id_document_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/ids/'),
        ),
        migrations.AddField(
            model_name='nursingprofessional',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/passports/'),
        ),
    ]
