# Generated by Django 5.1 on 2026-04-24 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0015_alter_healthstudent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='form_code',
            field=models.CharField(choices=[('NC1', 'NC1 - Provisional'), ('NC2', 'NC2 - Full'), ('G1', 'G1 - Graduand'), ('GD', 'GD'), ('PG', 'PG')], max_length=20),
        ),
    ]
