# Generated by Django 5.1 on 2026-04-29 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('workforce', '0017_expand_application_form_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='form_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='pathway',
            field=models.CharField(choices=[('local_nursing_graduate', 'Local Nursing Graduate (PNG)'), ('local_midwifery_graduate', 'Local Midwifery Graduate (PNG)'), ('overseas_nurse', 'Overseas Nurse'), ('overseas_midwife', 'Overseas Midwife'), ('special_case', 'Special Case'), ('other', 'Other')], default='other', max_length=40),
        ),
        migrations.AddField(
            model_name='application',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='application',
            name='profession_track',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='communityhealthworker',
            name='full_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='communityhealthworker',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('married', 'Married'), ('single', 'Single'), ('divorced', 'Divorced'), ('widow_widower', 'Widow/Widower'), ('other', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='communityhealthworker',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='communityhealthworker',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='communityhealthworker',
            name='province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='communityhealthworker',
            name='title',
            field=models.CharField(blank=True, choices=[('Miss', 'Miss'), ('Ms', 'Ms'), ('Mrs', 'Mrs'), ('Mr', 'Mr'), ('Sr', 'Sr'), ('Dr', 'Dr'), ('Prof', 'Prof')], max_length=20),
        ),
        migrations.AddField(
            model_name='healthstudent',
            name='full_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='healthstudent',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('married', 'Married'), ('single', 'Single'), ('divorced', 'Divorced'), ('widow_widower', 'Widow/Widower'), ('other', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='healthstudent',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='healthstudent',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='healthstudent',
            name='province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='healthstudent',
            name='title',
            field=models.CharField(blank=True, choices=[('Miss', 'Miss'), ('Ms', 'Ms'), ('Mrs', 'Mrs'), ('Mr', 'Mr'), ('Sr', 'Sr'), ('Dr', 'Dr'), ('Prof', 'Prof')], max_length=20),
        ),
        migrations.AddField(
            model_name='medicaldoctor',
            name='full_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicaldoctor',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('married', 'Married'), ('single', 'Single'), ('divorced', 'Divorced'), ('widow_widower', 'Widow/Widower'), ('other', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='medicaldoctor',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='medicaldoctor',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='medicaldoctor',
            name='province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='medicaldoctor',
            name='title',
            field=models.CharField(blank=True, choices=[('Miss', 'Miss'), ('Ms', 'Ms'), ('Mrs', 'Mrs'), ('Mr', 'Mr'), ('Sr', 'Sr'), ('Dr', 'Dr'), ('Prof', 'Prof')], max_length=20),
        ),
        migrations.AddField(
            model_name='midwife',
            name='full_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='midwife',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('married', 'Married'), ('single', 'Single'), ('divorced', 'Divorced'), ('widow_widower', 'Widow/Widower'), ('other', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='midwife',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='midwife',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='midwife',
            name='province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='midwife',
            name='title',
            field=models.CharField(blank=True, choices=[('Miss', 'Miss'), ('Ms', 'Ms'), ('Mrs', 'Mrs'), ('Mr', 'Mr'), ('Sr', 'Sr'), ('Dr', 'Dr'), ('Prof', 'Prof')], max_length=20),
        ),
        migrations.AddField(
            model_name='nurseaide',
            name='full_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nurseaide',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('married', 'Married'), ('single', 'Single'), ('divorced', 'Divorced'), ('widow_widower', 'Widow/Widower'), ('other', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='nurseaide',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='nurseaide',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='nurseaide',
            name='province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='nurseaide',
            name='title',
            field=models.CharField(blank=True, choices=[('Miss', 'Miss'), ('Ms', 'Ms'), ('Mrs', 'Mrs'), ('Mr', 'Mr'), ('Sr', 'Sr'), ('Dr', 'Dr'), ('Prof', 'Prof')], max_length=20),
        ),
        migrations.AddField(
            model_name='nursingprofessional',
            name='full_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nursingprofessional',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('married', 'Married'), ('single', 'Single'), ('divorced', 'Divorced'), ('widow_widower', 'Widow/Widower'), ('other', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='nursingprofessional',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='nursingprofessional',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='nursingprofessional',
            name='province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='nursingprofessional',
            name='title',
            field=models.CharField(blank=True, choices=[('Miss', 'Miss'), ('Ms', 'Ms'), ('Mrs', 'Mrs'), ('Mr', 'Mr'), ('Sr', 'Sr'), ('Dr', 'Dr'), ('Prof', 'Prof')], max_length=20),
        ),
        migrations.AddField(
            model_name='professionaldocument',
            name='document_label',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='professionaldocument',
            name='is_attached',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='professionaldocument',
            name='verification_signature',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='qualification',
            name='certificate_attached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qualification',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='qualification',
            name='date_completed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qualification',
            name='date_started',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qualification',
            name='institution_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='qualification',
            name='program_completed',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='qualification',
            name='transcript_attached',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='application',
            name='form_code',
            field=models.CharField(choices=[('MD1', 'MD1 - Medical Registration'), ('MD2', 'MD2 - Medical Renewal'), ('CHW1', 'CHW1 - CHW Registration'), ('G1', 'G1 - Graduate Nurses Checklist'), ('G2', 'G2 - List of New Graduate Nurses'), ('G3', 'G3 - Graduate Vitae'), ('G4', 'G4 - Statement of Competency (Nurses)'), ('G5', 'G5 - Statement of Competency (Midwives)'), ('G6', 'G6 - Graduate Midwives Checklist'), ('G7', 'G7 - List of Graduate Midwives'), ('NC1', 'NC1 - Application for Provisional Licence'), ('NC2', 'NC2 - Application for Full Licence'), ('NC3', 'NC3 - Renewal of Licence'), ('NC4', 'NC4 - Checklist for Provisional Licence'), ('NC5', 'NC5 - Full Registration & Licence'), ('NC6', 'NC6 - Competency for Full Licence Nursing'), ('NC7', 'NC7 - Competency for Full Licence Midwifery'), ('NC8', 'NC8 - Application for Temporary Licence'), ('NC9', 'NC9 - Checklist for Temporary Licence'), ('NC10', 'NC10 - Competency for Full Licence Child Nursing'), ('NC11', 'NC11 - Double Major Full Registration Checklist'), ('GD', 'GD'), ('PG', 'PG')], max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cpdrecord',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postinghistory',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='postinghistory',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professionaldocument',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='professionaldocument',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professionalphoto',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='professionalphoto',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EmploymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('employer_name', models.CharField(blank=True, max_length=255)),
                ('employer_address', models.TextField(blank=True)),
                ('position_held', models.CharField(blank=True, max_length=255)),
                ('duration_of_employment', models.CharField(blank=True, max_length=100)),
                ('employment_status', models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('studying', 'Studying'), ('unemployed', 'Unemployed'), ('other', 'Other')], max_length=30)),
                ('area_of_employment', models.CharField(blank=True, choices=[('government', 'Government'), ('private', 'Private'), ('church', 'Church'), ('ngo', 'NGOs'), ('other', 'Other')], max_length=30)),
                ('occupation', models.CharField(blank=True, max_length=255)),
                ('function_type', models.CharField(blank=True, max_length=255)),
                ('place_of_work', models.CharField(blank=True, max_length=255)),
                ('business_address', models.TextField(blank=True)),
                ('business_number', models.CharField(blank=True, max_length=50)),
                ('reasons_for_unemployment', models.TextField(blank=True)),
                ('employer_reference_attached', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='workforce_e_content_0c5d1d_idx')],
            },
        ),
    ]
