# Generated by Django 5.1 on 2026-04-29 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0018_application_form_title_application_pathway_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file_name', models.CharField(max_length=255)),
                ('source_file_path', models.TextField(blank=True)),
                ('source_kind', models.CharField(blank=True, default='workbook', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_sheets', models.PositiveIntegerField(default=0)),
                ('processed_sheets', models.PositiveIntegerField(default=0)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('processed_rows', models.PositiveIntegerField(default=0)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workforce_import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportedWorkbookSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(max_length=255)),
                ('sheet_type', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('raw_rows', models.PositiveIntegerField(default=0)),
                ('imported_rows', models.PositiveIntegerField(default=0)),
                ('skipped_rows', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='workforce.dataimportbatch')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('batch', 'sheet_name')},
            },
        ),
        migrations.CreateModel(
            name='PracticingLicenseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('provisional', 'Provisional Registration'), ('full', 'Full Registration'), ('temporary', 'Temporary Certificate'), ('practicing_license', 'Practicing License'), ('payment', 'Payment'), ('workforce_listing', 'Workforce Listing'), ('summary', 'Summary')], max_length=40)),
                ('target_model', models.CharField(choices=[('nursingprofessional', 'Nursing Professional'), ('midwife', 'Midwife'), ('medicaldoctor', 'Medical Doctor'), ('communityhealthworker', 'Community Health Worker'), ('nurseaide', 'Nurse Aide'), ('healthstudent', 'Health Student'), ('other', 'Other')], default='other', max_length=40)),
                ('source_sheet_name', models.CharField(max_length=255)),
                ('source_row', models.PositiveIntegerField(default=0)),
                ('record_year', models.PositiveIntegerField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('registration_no', models.CharField(blank=True, db_index=True, max_length=100)),
                ('practitioner_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('applicant_type', models.CharField(blank=True, max_length=20)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('qualification_name', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, db_index=True, max_length=150)),
                ('institution_name', models.CharField(blank=True, max_length=255)),
                ('workplace_address', models.TextField(blank=True)),
                ('province', models.CharField(blank=True, db_index=True, max_length=120)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('renewal_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('overseas_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('penalty_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('late_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=120)),
                ('payment_method', models.CharField(blank=True, max_length=120)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='workforce.dataimportbatch')),
                ('sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='workforce.importedworkbooksheet')),
            ],
            options={
                'ordering': ['-record_year', 'source_sheet_name', 'source_row'],
                'indexes': [models.Index(fields=['record_year', 'record_type'], name='workforce_p_record__b7671d_idx'), models.Index(fields=['source_sheet_name', 'record_type'], name='workforce_p_source__2e76a9_idx'), models.Index(fields=['registration_no', 'record_year'], name='workforce_p_registr_87aaa6_idx')],
                'unique_together': {('batch', 'source_sheet_name', 'source_row', 'record_type')},
            },
        ),
    ]
