# Generated by Django 5.1 on 2026-04-29 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('workforce', '0020_medical_board_application_forms'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingDataReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('registration_no', models.CharField(blank=True, db_index=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('professional_type', models.CharField(blank=True, db_index=True, max_length=80)),
                ('missing_fields', models.JSONField(blank=True, default=list)),
                ('missing_count', models.PositiveIntegerField(default=0)),
                ('source_label', models.CharField(blank=True, max_length=255)),
                ('source_row', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('under_review', 'Under Review'), ('notified', 'Notified'), ('resolved', 'Resolved')], db_index=True, default='under_review', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, default='medium', max_length=20)),
                ('notification_sent', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-missing_count', 'professional_type', 'full_name'],
                'indexes': [models.Index(fields=['status', 'professional_type'], name='workforce_m_status_c1ae87_idx'), models.Index(fields=['registration_no', 'status'], name='workforce_m_registr_eee356_idx')],
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
