# Generated by Django 5.1 on 2026-05-06 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0021_missingdatareview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationPathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathway_code', models.CharField(max_length=60)),
                ('pathway_name', models.CharField(max_length=255)),
                ('applicant_type', models.CharField(blank=True, max_length=60)),
                ('primary_form_code', models.CharField(max_length=20)),
                ('checklist_code', models.CharField(blank=True, max_length=60)),
                ('competency_framework_code', models.CharField(blank=True, max_length=60)),
                ('fee_rule_code', models.CharField(blank=True, max_length=60)),
                ('requires_payment', models.BooleanField(default=False)),
                ('requires_employer', models.BooleanField(default=False)),
                ('requires_institution', models.BooleanField(default=False)),
                ('requires_supervisor', models.BooleanField(default=False)),
                ('requires_registrar_approval', models.BooleanField(default=True)),
                ('creates_licence_type', models.CharField(blank=True, max_length=80)),
                ('public_visible', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('configuration', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['regulatory_body', 'sort_order', 'pathway_code'],
            },
        ),
        migrations.CreateModel(
            name='RegulatoryBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Regulatory bodies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeclarationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=255)),
                ('declaration_text', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('required_for_pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declaration_templates', to='workforce.applicationpathway')),
                ('regulatory_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declaration_templates', to='workforce.regulatorybody')),
            ],
            options={
                'ordering': ['regulatory_body', 'code'],
            },
        ),
        migrations.CreateModel(
            name='DynamicFormDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_code', models.CharField(max_length=20)),
                ('form_name', models.CharField(max_length=255)),
                ('version', models.CharField(default='2026.1', max_length=30)),
                ('sections', models.JSONField(blank=True, default=list)),
                ('fields', models.JSONField(blank=True, default=list)),
                ('validation_rules', models.JSONField(blank=True, default=list)),
                ('visibility_rules', models.JSONField(blank=True, default=list)),
                ('required_documents', models.JSONField(blank=True, default=list)),
                ('mapped_model_fields', models.JSONField(blank=True, default=dict)),
                ('active_from', models.DateField(blank=True, null=True)),
                ('active_to', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('pathway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_definitions', to='workforce.applicationpathway')),
                ('regulatory_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_definitions', to='workforce.regulatorybody')),
            ],
            options={
                'ordering': ['regulatory_body', 'form_code', '-version'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type_code', models.CharField(max_length=80)),
                ('label', models.CharField(max_length=255)),
                ('required', models.BooleanField(default=True)),
                ('required_for_applicant_type', models.CharField(blank=True, max_length=60)),
                ('accepts_multiple', models.BooleanField(default=False)),
                ('requires_certification', models.BooleanField(default=False)),
                ('requires_translation', models.BooleanField(default=False)),
                ('requires_expiry_date', models.BooleanField(default=False)),
                ('requires_issue_date', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workforce.documenttype')),
                ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requirements', to='workforce.applicationpathway')),
                ('form_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_requirements', to='workforce.dynamicformdefinition')),
            ],
            options={
                'ordering': ['pathway', 'sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='PolicyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=255)),
                ('document_url', models.TextField(blank=True)),
                ('version', models.CharField(default='2026.1', max_length=30)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('regulatory_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_documents', to='workforce.regulatorybody')),
            ],
            options={
                'ordering': ['regulatory_body', 'code', '-version'],
            },
        ),
        migrations.CreateModel(
            name='FeeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_rule_code', models.CharField(max_length=60)),
                ('label', models.CharField(max_length=255)),
                ('applicant_type', models.CharField(blank=True, max_length=60)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='PGK', max_length=10)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('pathway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_schedules', to='workforce.applicationpathway')),
                ('regulatory_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_schedules', to='workforce.regulatorybody')),
            ],
            options={
                'ordering': ['regulatory_body', 'fee_rule_code', 'applicant_type'],
            },
        ),
        migrations.AddField(
            model_name='applicationpathway',
            name='regulatory_body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_pathways', to='workforce.regulatorybody'),
        ),
        migrations.CreateModel(
            name='ApplicationFormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_code', models.CharField(max_length=20)),
                ('form_version', models.CharField(default='2026.1', max_length=30)),
                ('response_json', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_responses', to='workforce.application')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_form_responses', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_form_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('application', 'form_code', 'form_version')},
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=40)),
                ('new_status', models.CharField(max_length=40)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='workforce.application')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('supporting_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workforce.professionaldocument')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['application', 'new_status'], name='workforce_a_applica_4ec277_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('entity_type', models.CharField(max_length=120)),
                ('entity_id', models.CharField(blank=True, max_length=80)),
                ('old_values_json', models.JSONField(blank=True, default=dict)),
                ('new_values_json', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'entity_type'], name='workforce_a_action_cf047f_idx'), models.Index(fields=['created_at'], name='workforce_a_created_f2de9e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApplicantDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to='workforce.application')),
                ('declaration_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accepted_declarations', to='workforce.declarationtemplate')),
            ],
            options={
                'unique_together': {('application', 'declaration_template')},
            },
        ),
        migrations.CreateModel(
            name='ApplicationChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_uploaded', 'Not Uploaded'), ('uploaded', 'Uploaded'), ('verification_pending', 'Verification Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('waived', 'Waived')], default='not_uploaded', max_length=30)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='workforce.application')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_items', to='workforce.professionaldocument')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document_requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_items', to='workforce.documentrequirement')),
            ],
            options={
                'ordering': ['application', 'document_requirement__sort_order'],
                'indexes': [models.Index(fields=['application', 'status'], name='workforce_a_applica_a7adf4_idx')],
                'unique_together': {('application', 'document_requirement')},
            },
        ),
        migrations.AddIndex(
            model_name='documentrequirement',
            index=models.Index(fields=['document_type_code', 'active'], name='workforce_d_documen_b6ec0c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentrequirement',
            unique_together={('pathway', 'document_type_code')},
        ),
        migrations.AlterUniqueTogether(
            name='policydocument',
            unique_together={('regulatory_body', 'code', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='feeschedule',
            unique_together={('regulatory_body', 'fee_rule_code', 'applicant_type', 'effective_from')},
        ),
        migrations.AddIndex(
            model_name='dynamicformdefinition',
            index=models.Index(fields=['form_code', 'active'], name='workforce_d_form_co_927453_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dynamicformdefinition',
            unique_together={('regulatory_body', 'form_code', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='declarationtemplate',
            unique_together={('regulatory_body', 'code', 'required_for_pathway')},
        ),
        migrations.AddIndex(
            model_name='applicationpathway',
            index=models.Index(fields=['pathway_code'], name='workforce_a_pathway_b273b5_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationpathway',
            index=models.Index(fields=['active', 'public_visible'], name='workforce_a_active_b09bbf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='applicationpathway',
            unique_together={('regulatory_body', 'pathway_code')},
        ),
    ]
