# Generated by Django 5.1 on 2026-05-19 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_enquirymessageattachment'),
        ('workforce', '0023_deceasednotification_employerverificationrequest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuedLicenceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('authority_to_practice', 'Authority to Practice'), ('full_licence', 'Full Licence'), ('provisional_licence', 'Provisional Licence'), ('temporary_licence', 'Temporary Licence')], max_length=40)),
                ('document_number', models.CharField(max_length=100, unique=True)),
                ('file', models.FileField(upload_to='issued_licence_documents/%Y/%m/')),
                ('recipient_name', models.CharField(blank=True, max_length=255)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('delivery_channel', models.CharField(choices=[('mailbox', 'Platform mailbox'), ('email', 'Direct email'), ('both', 'Mailbox and email')], default='both', max_length=20)),
                ('email_sent', models.BooleanField(default=False)),
                ('mailbox_sent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('sent', 'Sent'), ('failed', 'Failed')], default='generated', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_documents', to='workforce.application')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_licence_documents', to=settings.AUTH_USER_MODEL)),
                ('mailbox_thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_licence_documents', to='notifications.enquirythread')),
                ('practicing_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_documents', to='workforce.practicinglicenserecord')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_licence_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['document_type', 'issued_at'], name='workforce_i_documen_05ebae_idx'), models.Index(fields=['status', 'delivery_channel'], name='workforce_i_status_4802e0_idx')],
            },
        ),
    ]
