# Generated by Django 5.1 on 2026-05-19 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0024_issuedlicencedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentrecord',
            name='district',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='employmentrecord',
            name='employment_sector',
            field=models.CharField(blank=True, choices=[('public', 'Public'), ('church', 'Church'), ('private', 'Private'), ('ngo', 'NGO'), ('overseas', 'Overseas'), ('unknown', 'Unknown')], max_length=30),
        ),
        migrations.AddField(
            model_name='employmentrecord',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employmentrecord',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workforce.facility'),
        ),
        migrations.AddField(
            model_name='employmentrecord',
            name='facility_name_raw',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employmentrecord',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employmentrecord',
            name='position_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employmentrecord',
            name='province',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='employmentrecord',
            name='review_status',
            field=models.CharField(blank=True, choices=[('staged', 'Staged'), ('accepted', 'Accepted'), ('promoted', 'Promoted'), ('rejected', 'Rejected')], max_length=30),
        ),
        migrations.AddField(
            model_name='employmentrecord',
            name='source_file',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employmentrecord',
            name='source_row',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employmentrecord',
            name='source_sheet',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employmentrecord',
            name='source_submission',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employmentrecord',
            name='source_type',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='employmentrecord',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employmentrecord',
            name='workforce_function',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='employmentrecord',
            name='area_of_employment',
            field=models.CharField(blank=True, choices=[('public', 'Public'), ('church', 'Church'), ('ngo', 'NGO'), ('overseas', 'Overseas'), ('unknown', 'Unknown'), ('government', 'Government'), ('private', 'Private'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='employmentrecord',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('employed', 'Employed'), ('inactive', 'Inactive'), ('retired', 'Retired'), ('deceased', 'Deceased'), ('overseas', 'Overseas'), ('unknown', 'Unknown'), ('full_time', 'Full Time'), ('part_time', 'Part Time'), ('studying', 'Studying'), ('unemployed', 'Unemployed'), ('other', 'Other')], max_length=30),
        ),
    ]
