# Generated by Django 5.1 on 2026-05-27 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0027_traininginstitution_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicinglicenserecord',
            name='record_type',
            field=models.CharField(choices=[('provisional', 'Provisional Registration'), ('full', 'Full-Licence Applicant'), ('full_approved', 'Full-Licence Approved'), ('temporary', 'Temporary Certificate'), ('practicing_license', 'Practicing License'), ('payment', 'Payment'), ('workforce_listing', 'Workforce Listing'), ('summary', 'Summary')], max_length=40),
        ),
    ]
