# Generated by Django 5.1 on 2026-07-24 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('workforce', '0029_alter_application_form_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalPrivilege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('privilege_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('conditional', 'Approved with conditions'), ('suspended', 'Suspended'), ('revoked', 'Revoked'), ('expired', 'Expired')], db_index=True, default='requested', max_length=30)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, db_index=True, null=True)),
                ('decision_reference', models.CharField(blank=True, max_length=120)),
                ('conditions_summary', models.TextField(blank=True)),
                ('evidence_summary', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_clinical_privileges', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_privileges', to='workforce.facility')),
            ],
            options={
                'ordering': ['privilege_name', '-updated_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id', 'status'], name='workforce_c_content_0d2593_idx'), models.Index(fields=['status', 'expiry_date'], name='workforce_c_status_d086fd_idx')],
            },
        ),
        migrations.CreateModel(
            name='CredentialVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('credential_type', models.CharField(choices=[('qualification', 'Qualification'), ('specialist_certificate', 'Specialist certificate'), ('fellowship', 'Fellowship'), ('registration', 'Registration evidence'), ('cpd', 'CPD evidence'), ('other', 'Other evidence')], default='qualification', max_length=40)),
                ('credential_title', models.CharField(max_length=255)),
                ('issuing_institution', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('reference_number', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending verification'), ('institution_check', 'Institution check'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], db_index=True, default='pending', max_length=30)),
                ('evidence_summary', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', 'credential_title'],
                'indexes': [models.Index(fields=['content_type', 'object_id', 'status'], name='workforce_c_content_afea77_idx'), models.Index(fields=['credential_type', 'status'], name='workforce_c_credent_9a689c_idx')],
            },
        ),
        migrations.CreateModel(
            name='FacilityAccreditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accreditation_type', models.CharField(choices=[('hospital', 'Hospital'), ('clinic', 'Clinic'), ('private_practice', 'Private practice'), ('specialist_centre', 'Specialist centre'), ('diagnostic_facility', 'Diagnostic facility'), ('training_college', 'Training college'), ('other', 'Other')], default='other', max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under review'), ('accredited', 'Accredited'), ('conditional', 'Conditionally accredited'), ('suspended', 'Suspended'), ('expired', 'Expired'), ('not_accredited', 'Not accredited')], db_index=True, default='under_review', max_length=30)),
                ('reference_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('compliance_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_inspection_date', models.DateField(blank=True, null=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, db_index=True, null=True)),
                ('conditions_summary', models.TextField(blank=True)),
                ('evidence_summary', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_accreditations', to='workforce.facility')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_facility_accreditations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['facility__name', '-updated_at'],
                'indexes': [models.Index(fields=['status', 'valid_until'], name='workforce_f_status_ec60c4_idx'), models.Index(fields=['accreditation_type', 'status'], name='workforce_f_accredi_66e3a6_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalProfileUpdateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('office_scope', models.CharField(choices=[('nursing', 'Nursing Council'), ('medical', 'Medical Board')], db_index=True, max_length=20)),
                ('update_type', models.CharField(choices=[('contact', 'Contact details'), ('workplace', 'Current workplace'), ('qualification', 'Qualification or specialist credential'), ('cpd', 'CPD activity'), ('clinical_privilege', 'Clinical privilege')], db_index=True, max_length=40)),
                ('proposed_changes', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True)),
                ('evidence', models.FileField(blank=True, null=True, upload_to='profile_update_requests/%Y/%m/')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='submitted', max_length=30)),
                ('reviewer_note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professional_profile_update_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_professional_profile_update_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['office_scope', 'status', 'submitted_at'], name='workforce_p_office__cff383_idx'), models.Index(fields=['content_type', 'object_id', 'status'], name='workforce_p_content_4ab4c3_idx')],
            },
        ),
    ]
