from django.urls import path

from .views import (
    AdvancedDashboardView,
    WorkforceFlowDashboardView,
    export_workforce_flow_pdf,
    generate_csv_report,
    generate_registered_nurses_pdf, admin_dashboard, registrar_dashboard,
    registrar_individual_records, data_quality_reviews_table,
    dashboard_license_record_table,
    nursing_analytics_fact_detail,
    nursing_analytics_pathway_detail,
    nursing_council_analytics_drilldown,
    nursing_council_analytics_summary,
    nurse_dashboard, nurse_aide_dashboard, chw_dashboard, doctor_dashboard, student_dashboard, main_dashboard,
    nursing_council_board_portal, nursing_council_portal, nursing_frequent_records, medical_board_portal, medical_staff_portal, submit_receipt,
    viewer_dashboard,
    execute_management_command, upload_atp_workbook_import, upload_full_licence_workbook_import,
    upload_provisional_workbook_import, fee_structure, dashboard_search,
    export_monthly_analytics_excel,
    export_monthly_analytics_pdf,
    export_registered_nurses_excel,
    export_yearly_analytics_excel,
    export_yearly_analytics_pdf,
    financial_forecast_dashboard,
    export_financial_forecast_excel_view,
    export_financial_forecast_pdf_view,
    export_financial_forecast_docx_view,
    export_minister_brief_docx,
    export_registrar_secretary_brief_docx,
    staff_ai_assistant,
    staff_ai_chat,
    staff_ai_feedback,
    staff_ai_chat_stream,
    duplicate_review_workflow,
    duplicate_review_update,
    facilities_directory,
    facility_worker_detail,
    forum_category_detail,
    forum_index,
    forum_moderate_post,
    forum_topic_detail,
    imported_facility_worker_detail,
    institution_graduand_detail,
    nhwa_toolkit,
    platform_standards_alignment,
    review_centre,
    production_readiness_dashboard,
    production_readiness_missing_review_update,
    nursing_council_public_profile,
    public_faqs,
    platform_resilience_status,
    workforce_map,
)
from ..workforce.views import professional_dashboard
from apps.mobile_intake.views import mobile_intake_detail, mobile_intake_queue, mobile_production_readiness

urlpatterns = [
    path('', AdvancedDashboardView.as_view(), name='advanced_dashboard'),
    path('flow/', WorkforceFlowDashboardView.as_view(), name='workforce_flow'),
    path('reports/dashboard/pdf/', export_workforce_flow_pdf, name='export_dashboard_pdf'),
    path('reports/monthly/pdf/', export_monthly_analytics_pdf, name='export_monthly_analytics_pdf'),
    path('reports/monthly/excel/', export_monthly_analytics_excel, name='export_monthly_analytics_excel'),
    path('reports/yearly/pdf/', export_yearly_analytics_pdf, name='export_yearly_analytics_pdf'),
    path('reports/yearly/excel/', export_yearly_analytics_excel, name='export_yearly_analytics_excel'),
    path('reports/financial/', financial_forecast_dashboard, name='financial_forecast_dashboard'),
    path('reports/financial/excel/', export_financial_forecast_excel_view, name='export_financial_forecast_excel'),
    path('reports/financial/pdf/', export_financial_forecast_pdf_view, name='export_financial_forecast_pdf'),
    path('reports/financial/docx/', export_financial_forecast_docx_view, name='export_financial_forecast_docx'),
    path('reports/nurses/pdf/', generate_registered_nurses_pdf, name='nurses_pdf'),
    path('reports/registered-nurses/excel/', export_registered_nurses_excel, name='registered_nurses_excel'),
    path('reports/<str:report_type>/csv/', generate_csv_report, name='report_csv'),
    path('briefs/minister/docx/', export_minister_brief_docx, name='export_minister_brief_docx'),
    path('briefs/registrar-secretary/docx/', export_registrar_secretary_brief_docx, name='export_registrar_secretary_brief_docx'),
    path('staff-ai/', staff_ai_assistant, name='staff_ai_assistant'),
    path('public/nursing-council/profile/', nursing_council_public_profile, name='nursing_council_public_profile'),
    path('public/faqs/', public_faqs, name='public_faqs'),
    path('public/forum/', forum_index, name='forum_index'),
    path('public/forum/<slug:slug>/', forum_category_detail, name='forum_category_detail'),
    path('public/forum/<slug:category_slug>/<slug:topic_slug>/', forum_topic_detail, name='forum_topic_detail'),
    path('public/map/', workforce_map, name='workforce_map'),
    path('facilities/', facilities_directory, name='facilities_directory'),
    path('facilities/<int:facility_id>/workers/', facility_worker_detail, name='facility_worker_detail'),
    path('facilities/workplace/', imported_facility_worker_detail, name='imported_facility_worker_detail'),
    path('institutions/<int:institution_id>/graduands/', institution_graduand_detail, name='institution_graduand_detail'),
    path('reviews/', review_centre, name='review_centre'),
    path('forum/posts/<int:post_id>/moderate/', forum_moderate_post, name='forum_moderate_post'),
    path('duplicate-reviews/', duplicate_review_workflow, name='duplicate_review_workflow'),
    path('duplicate-reviews/<int:review_id>/update/', duplicate_review_update, name='duplicate_review_update'),
    path('nhwa-toolkit/', nhwa_toolkit, name='nhwa_toolkit'),
    path('standards-alignment/', platform_standards_alignment, name='platform_standards_alignment'),
    path('production-readiness/', production_readiness_dashboard, name='production_readiness_dashboard'),
    path('platform-resilience/status/', platform_resilience_status, name='platform_resilience_status'),
    path('production-readiness/mobile/', mobile_production_readiness, name='mobile_production_readiness'),
    path('production-readiness/missing-review/<int:review_id>/update/', production_readiness_missing_review_update, name='production_readiness_missing_review_update'),
    path('mobile-intake/', mobile_intake_queue, name='mobile_intake_queue'),
    path('mobile-intake/<uuid:submission_uuid>/', mobile_intake_detail, name='mobile_intake_detail'),
    path('staff-ai/chat/', staff_ai_chat, name='staff_ai_chat'),
    path('staff-ai/feedback/', staff_ai_feedback, name='staff_ai_feedback'),
    path('staff-ai/chat/stream/', staff_ai_chat_stream, name='staff_ai_chat_stream'),

# Portal-specific dashboards
    path('nursing-council/', nursing_council_portal, name='nursing_council_portal'),
    path('nursing-council/board/', nursing_council_board_portal, name='nursing_council_board_portal'),
    path('nursing-council/analytics/summary/', nursing_council_analytics_summary, name='nursing_council_analytics_summary'),
    path('nursing-council/analytics/drilldown/', nursing_council_analytics_drilldown, name='nursing_council_analytics_drilldown'),
    path('nursing-council/analytics/facts/<int:fact_id>/', nursing_analytics_fact_detail, name='nursing_analytics_fact_detail'),
    path('nursing-council/analytics/pathways/<int:fact_id>/', nursing_analytics_pathway_detail, name='nursing_analytics_pathway_detail'),
    path('nursing-council/frequent-records/', nursing_frequent_records, name='nursing_frequent_records'),
    path('nursing-council/atp-import/upload/', upload_atp_workbook_import, name='upload_atp_workbook_import'),
    path('nursing-council/full-licence-import/upload/', upload_full_licence_workbook_import, name='upload_full_licence_workbook_import'),
    path('nursing-council/provisional-import/upload/', upload_provisional_workbook_import, name='upload_provisional_workbook_import'),
    path('medical-board/', medical_board_portal, name='medical_board_portal'),
    path('graduand-portal/', student_dashboard, name='graduand_portal'),
    path('medical-staff/', medical_staff_portal, name='medical_staff_portal'),

# Clean short URLs for dashboards
    path('admin/', admin_dashboard, name='admin_dashboard'),
    path('registrar/', registrar_dashboard, name='registrar_dashboard'),
    path('individual-records/', registrar_individual_records, name='registrar_individual_records'),
    path('data-quality/reviews/table/', data_quality_reviews_table, name='data_quality_reviews_table'),
    path('licence-records/<slug:table_key>/data/', dashboard_license_record_table, name='dashboard_license_record_table'),
    path('professional/', professional_dashboard, name='professional_dashboard'),
    path('nurse/', nurse_dashboard, name='nurse_dashboard'),
    path('nurse-aide/', nurse_aide_dashboard, name='nurse_aide_dashboard'),
    path('chw/', chw_dashboard, name='chw_dashboard'),
    path('doctor/', doctor_dashboard, name='doctor_dashboard'),
    path('graduand/', student_dashboard, name='graduand_dashboard'),
    path('student/', student_dashboard, name='student_dashboard'),
    path('viewer/', viewer_dashboard, name='viewer_dashboard'),
    path('main/', main_dashboard, name='main_dashboard'),
    path('search/', dashboard_search, name='dashboard_search'),
    path('receipts/submit/', submit_receipt, name='submit_receipt'),
    path('execute-command/', execute_management_command, name='execute_management_command'),
    path('fee-structure/', fee_structure, name='fee_structure'),
]
