from django.urls import path

from .views import (
    AdvancedDashboardView,
    WorkforceFlowDashboardView,
    export_workforce_flow_pdf,
    generate_csv_report,
    generate_registered_nurses_pdf, admin_dashboard, registrar_dashboard,
    registrar_individual_records, data_quality_reviews_table,
    nurse_dashboard, nurse_aide_dashboard, chw_dashboard, doctor_dashboard, student_dashboard, main_dashboard,
    nursing_council_portal, nursing_frequent_records, medical_board_portal, submit_receipt,
    viewer_dashboard,
    execute_management_command, fee_structure, dashboard_search,
    export_monthly_analytics_excel,
    export_monthly_analytics_pdf,
    export_yearly_analytics_excel,
    export_yearly_analytics_pdf,
    financial_forecast_dashboard,
    export_financial_forecast_excel_view,
    export_financial_forecast_pdf_view,
    export_financial_forecast_docx_view,
    export_minister_brief_docx,
    export_registrar_secretary_brief_docx,
    staff_ai_assistant,
    staff_ai_chat,
    duplicate_review_workflow,
    duplicate_review_update,
    platform_standards_alignment,
    production_readiness_dashboard,
    production_readiness_missing_review_update,
)
from ..workforce.views import professional_dashboard

urlpatterns = [
    path('', AdvancedDashboardView.as_view(), name='advanced_dashboard'),
    path('flow/', WorkforceFlowDashboardView.as_view(), name='workforce_flow'),
    path('reports/dashboard/pdf/', export_workforce_flow_pdf, name='export_dashboard_pdf'),
    path('reports/monthly/pdf/', export_monthly_analytics_pdf, name='export_monthly_analytics_pdf'),
    path('reports/monthly/excel/', export_monthly_analytics_excel, name='export_monthly_analytics_excel'),
    path('reports/yearly/pdf/', export_yearly_analytics_pdf, name='export_yearly_analytics_pdf'),
    path('reports/yearly/excel/', export_yearly_analytics_excel, name='export_yearly_analytics_excel'),
    path('reports/financial/', financial_forecast_dashboard, name='financial_forecast_dashboard'),
    path('reports/financial/excel/', export_financial_forecast_excel_view, name='export_financial_forecast_excel'),
    path('reports/financial/pdf/', export_financial_forecast_pdf_view, name='export_financial_forecast_pdf'),
    path('reports/financial/docx/', export_financial_forecast_docx_view, name='export_financial_forecast_docx'),
    path('reports/nurses/pdf/', generate_registered_nurses_pdf, name='nurses_pdf'),
    path('reports/<str:report_type>/csv/', generate_csv_report, name='report_csv'),
    path('briefs/minister/docx/', export_minister_brief_docx, name='export_minister_brief_docx'),
    path('briefs/registrar-secretary/docx/', export_registrar_secretary_brief_docx, name='export_registrar_secretary_brief_docx'),
    path('staff-ai/', staff_ai_assistant, name='staff_ai_assistant'),
    path('duplicate-reviews/', duplicate_review_workflow, name='duplicate_review_workflow'),
    path('duplicate-reviews/<int:review_id>/update/', duplicate_review_update, name='duplicate_review_update'),
    path('standards-alignment/', platform_standards_alignment, name='platform_standards_alignment'),
    path('production-readiness/', production_readiness_dashboard, name='production_readiness_dashboard'),
    path('production-readiness/missing-review/<int:review_id>/update/', production_readiness_missing_review_update, name='production_readiness_missing_review_update'),
    path('staff-ai/chat/', staff_ai_chat, name='staff_ai_chat'),

# Portal-specific dashboards
    path('nursing-council/', nursing_council_portal, name='nursing_council_portal'),
    path('nursing-council/frequent-records/', nursing_frequent_records, name='nursing_frequent_records'),
    path('medical-board/', medical_board_portal, name='medical_board_portal'),
    path('graduand-portal/', student_dashboard, name='graduand_portal'),
    path('medical-staff/', chw_dashboard, name='medical_staff_portal'),

# Clean short URLs for dashboards
    path('admin/', admin_dashboard, name='admin_dashboard'),
    path('registrar/', registrar_dashboard, name='registrar_dashboard'),
    path('individual-records/', registrar_individual_records, name='registrar_individual_records'),
    path('data-quality/reviews/table/', data_quality_reviews_table, name='data_quality_reviews_table'),
    path('professional/', professional_dashboard, name='professional_dashboard'),
    path('nurse/', nurse_dashboard, name='nurse_dashboard'),
    path('nurse-aide/', nurse_aide_dashboard, name='nurse_aide_dashboard'),
    path('chw/', chw_dashboard, name='chw_dashboard'),
    path('doctor/', doctor_dashboard, name='doctor_dashboard'),
    path('graduand/', student_dashboard, name='graduand_dashboard'),
    path('student/', student_dashboard, name='student_dashboard'),
    path('viewer/', viewer_dashboard, name='viewer_dashboard'),
    path('main/', main_dashboard, name='main_dashboard'),
    path('search/', dashboard_search, name='dashboard_search'),
    path('receipts/submit/', submit_receipt, name='submit_receipt'),
    path('execute-command/', execute_management_command, name='execute_management_command'),
    path('fee-structure/', fee_structure, name='fee_structure'),
]
