# Generated by Django 5.1 on 2026-04-12 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetencyAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('assessment_type', models.CharField(max_length=100)),
                ('assessment_date', models.DateField()),
                ('supervisor_name', models.CharField(max_length=100)),
                ('overall_recommendation', models.CharField(choices=[('competent', 'Competent'), ('not_competent', 'Not Competent')], max_length=50)),
                ('checklist_completed', models.BooleanField(default=False)),
                ('attached_logbook', models.FileField(blank=True, null=True, upload_to='competency/')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='CPDRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('training_type', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('hours_credits', models.FloatField(default=0)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='cpd/')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
