# Generated by Django 5.1 on 2026-04-12 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competencyassessment',
            name='overall_recommendation',
            field=models.CharField(choices=[('competent', 'Competent'), ('not_competent', 'Not Competent'), ('needs_improvement', 'Needs Improvement')], max_length=50),
        ),
    ]
