# Generated by Django 5.1 on 2026-04-16 05:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competency', '0002_alter_competencyassessment_overall_recommendation'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpdrecord',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='competencyassessment',
            name='attached_logbook',
        ),
        migrations.RemoveField(
            model_name='competencyassessment',
            name='checklist_completed',
        ),
        migrations.RemoveField(
            model_name='competencyassessment',
            name='overall_recommendation',
        ),
        migrations.AddField(
            model_name='competencyassessment',
            name='assessment_name',
            field=models.CharField(default='Initial Assessment', max_length=255),
        ),
        migrations.AddField(
            model_name='competencyassessment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competencyassessment',
            name='is_passed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='competencyassessment',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='competencyassessment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='competencyassessment',
            name='assessment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='competencyassessment',
            name='assessment_type',
            field=models.CharField(default='standard', max_length=100),
        ),
        migrations.AlterField(
            model_name='competencyassessment',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_assessments', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='competencyassessment',
            name='supervisor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='competencyassessment',
            index=models.Index(fields=['content_type', 'object_id'], name='competency__content_0f312b_idx'),
        ),
        migrations.AddIndex(
            model_name='competencyassessment',
            index=models.Index(fields=['assessment_date'], name='competency__assessm_141340_idx'),
        ),
        migrations.DeleteModel(
            name='CPDRecord',
        ),
    ]
