# Generated by Django 5.1 on 2026-04-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competency', '0003_remove_cpdrecord_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencyassessment',
            name='competency_domains',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='competencyassessment',
            name='form_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='competencyassessment',
            name='profession_track',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='competencyassessment',
            name='supervisor_assessment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='competencyassessment',
            name='supervisor_signature',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='competencyassessment',
            name='verification_signature',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
