# Generated by Django 5.1 on 2026-04-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notified_expiry',
            field=models.BooleanField(default=False),
        ),
    ]
