# Generated by Django 5.1 on 2026-05-17 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0004_enquirymailboxstate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enquirythread',
            name='delivery_channel',
            field=models.CharField(choices=[('office', 'Office enquiry'), ('mailbox', 'Platform mailbox'), ('email', 'Direct email'), ('both', 'Mailbox and email')], default='office', max_length=20),
        ),
        migrations.AddField(
            model_name='enquirythread',
            name='recipient_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='enquirythread',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='enquirythread',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='enquirythread',
            name='recipient_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquirythread',
            name='recipient_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_enquiry_threads', to=settings.AUTH_USER_MODEL),
        ),
    ]
