# Generated by Django 5.1 on 2026-05-18 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_notification_options_notification_read_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquirymailboxstate',
            name='last_read_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='notifications.enquirymessage'),
        ),
        migrations.AddField(
            model_name='enquirymailboxstate',
            name='read_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
