# Generated by Django 5.1 on 2026-05-19 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_enquirymailboxstate_last_read_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryMessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='mailbox_attachments/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='notifications.enquirymessage')),
            ],
            options={
                'ordering': ['uploaded_at', 'id'],
            },
        ),
    ]
